import type { AbilityDef } from "@ton-abyss/shared";

export const ABILITIES: Record<string, AbilityDef> = {
  // ------ PLAYER BASIC ------
  basic_strike: {
    id: "basic_strike",
    name: "Удар",
    kind: "attack",
    element: "physical",
    manaCost: 0,
    cooldown: 0,
    baseDamage: 10,
    scaling: { attack: 1.0 },
    targets: "enemy",
    description: "Обычная атака оружием.",
  },
  power_strike: {
    id: "power_strike",
    name: "Сокрушающий удар",
    kind: "attack",
    element: "physical",
    manaCost: 8,
    cooldown: 2,
    baseDamage: 22,
    scaling: { attack: 1.4 },
    targets: "enemy",
    description: "Мощный удар с шансом пробить блок.",
  },
  shield_wall: {
    id: "shield_wall",
    name: "Стена щита",
    kind: "buff",
    element: "physical",
    manaCost: 10,
    cooldown: 4,
    effects: [{ id: "fortify", duration: 2, potency: 0.35 }],
    targets: "self",
    description: "На 2 хода получаемый урон -35%.",
  },
  rune_bolt: {
    id: "rune_bolt",
    name: "Руническая молния",
    kind: "spell",
    element: "shock",
    manaCost: 12,
    cooldown: 1,
    baseDamage: 18,
    scaling: { spellPower: 1.2 },
    targets: "enemy",
    description: "Разряд молнии, может оглушить.",
    effects: [{ id: "shock", duration: 2, potency: 0.05 }],
  },
  rune_ignite: {
    id: "rune_ignite",
    name: "Руна пламени",
    kind: "spell",
    element: "fire",
    manaCost: 16,
    cooldown: 2,
    baseDamage: 14,
    scaling: { spellPower: 1.1 },
    targets: "enemy",
    description: "Поджигает цель на 3 хода.",
    effects: [{ id: "burn", duration: 3, potency: 6, stacks: 1 }],
  },
  void_drain: {
    id: "void_drain",
    name: "Высасывание Бездны",
    kind: "spell",
    element: "void",
    manaCost: 14,
    cooldown: 2,
    baseDamage: 20,
    scaling: { spellPower: 1.3 },
    targets: "enemy",
    description: "Наносит урон тенью и восстанавливает HP равное 40% урона.",
  },
  void_curse: {
    id: "void_curse",
    name: "Проклятие",
    kind: "debuff",
    element: "void",
    manaCost: 18,
    cooldown: 3,
    effects: [
      { id: "curse", duration: 3, potency: 0.2 },
      { id: "mark", duration: 3, potency: 0.15 },
    ],
    targets: "enemy",
    description: "Метка усиливает получаемый урон +15% на 3 хода.",
  },
  beast_slash: {
    id: "beast_slash",
    name: "Рассечение",
    kind: "attack",
    element: "physical",
    manaCost: 6,
    cooldown: 1,
    baseDamage: 12,
    scaling: { attack: 1.1 },
    effects: [{ id: "bleed", duration: 3, potency: 5 }],
    targets: "enemy",
    description: "Глубокий порез — кровотечение на 3 хода.",
  },
  rally_pet: {
    id: "rally_pet",
    name: "Клич звериного друга",
    kind: "buff",
    element: "physical",
    manaCost: 12,
    cooldown: 5,
    effects: [{ id: "haste", duration: 3, potency: 0.25 }],
    targets: "ally",
    description: "Питомец получает +25% скорости/урона на 3 хода.",
  },
  // ------ POTIONS / UTILITY ------
  lesser_heal: {
    id: "lesser_heal",
    name: "Слабое лечение",
    kind: "heal",
    element: "holy",
    manaCost: 10,
    cooldown: 3,
    baseDamage: 30,
    scaling: { spellPower: 0.8 },
    targets: "self",
  },

  // ------ ENEMY ------
  e_bite: {
    id: "e_bite",
    name: "Укус",
    kind: "attack",
    element: "physical",
    manaCost: 0,
    cooldown: 0,
    baseDamage: 8,
    scaling: { attack: 1.0 },
    targets: "enemy",
  },
  e_slam: {
    id: "e_slam",
    name: "Сокрушительный удар",
    kind: "attack",
    element: "physical",
    manaCost: 0,
    cooldown: 2,
    baseDamage: 16,
    scaling: { attack: 1.3 },
    targets: "enemy",
  },
  e_shadow_fang: {
    id: "e_shadow_fang",
    name: "Клык теней",
    kind: "spell",
    element: "void",
    manaCost: 0,
    cooldown: 3,
    baseDamage: 22,
    scaling: { spellPower: 1.2 },
    targets: "enemy",
    effects: [{ id: "curse", duration: 2, potency: 0.15 }],
  },
  e_frost_lance: {
    id: "e_frost_lance",
    name: "Копьё льда",
    kind: "spell",
    element: "frost",
    manaCost: 0,
    cooldown: 2,
    baseDamage: 18,
    scaling: { spellPower: 1.1 },
    targets: "enemy",
    effects: [{ id: "chill", duration: 2, potency: 0.3 }],
  },
  e_infernal_roar: {
    id: "e_infernal_roar",
    name: "Инфернальный рык",
    kind: "debuff",
    element: "fire",
    manaCost: 0,
    cooldown: 4,
    targets: "enemy",
    effects: [
      { id: "weakness", duration: 2, potency: 0.25 },
      { id: "burn", duration: 3, potency: 8 },
    ],
  },
  e_abyssal_gaze: {
    id: "e_abyssal_gaze",
    name: "Взор Бездны",
    kind: "debuff",
    element: "void",
    manaCost: 0,
    cooldown: 5,
    targets: "enemy",
    effects: [
      { id: "silence", duration: 1, potency: 1 },
      { id: "mark", duration: 3, potency: 0.4 },
    ],
  },
};
