import type { AbilityDef } from "@ton-abyss/shared";

export const ABILITIES: Record<string, AbilityDef> = {
  // ------ PLAYER BASIC ------
  basic_strike: {
    id: "basic_strike",
    name: "Удар",
    kind: "attack",
    element: "physical",
    manaCost: 0,
    cooldown: 0,
    baseDamage: 10,
    scaling: { attack: 1.0 },
    targets: "enemy",
    description: "Обычная атака оружием.",
  },
  power_strike: {
    id: "power_strike",
    name: "Сокрушающий удар",
    kind: "attack",
    element: "physical",
    manaCost: 8,
    cooldown: 2,
    baseDamage: 22,
    scaling: { attack: 1.4 },
    targets: "enemy",
    description: "Мощный удар с шансом пробить блок.",
  },
  shield_wall: {
    id: "shield_wall",
    name: "Стена щита",
    kind: "buff",
    element: "physical",
    manaCost: 10,
    cooldown: 4,
    effects: [{ id: "fortify", duration: 2, potency: 0.35 }],
    targets: "self",
    description: "На 2 хода получаемый урон -35%.",
  },
  rune_bolt: {
    id: "rune_bolt",
    name: "Руническая молния",
    kind: "spell",
    element: "shock",
    manaCost: 12,
    cooldown: 1,
    baseDamage: 18,
    scaling: { spellPower: 1.2 },
    targets: "enemy",
    description: "Разряд молнии, может оглушить.",
    effects: [{ id: "shock", duration: 2, potency: 0.05 }],
  },
  rune_ignite: {
    id: "rune_ignite",
    name: "Руна пламени",
    kind: "spell",
    element: "fire",
    manaCost: 16,
    cooldown: 2,
    baseDamage: 14,
    scaling: { spellPower: 1.1 },
    targets: "enemy",
    description: "Поджигает цель на 3 хода.",
    effects: [{ id: "burn", duration: 3, potency: 6, stacks: 1 }],
  },
  void_drain: {
    id: "void_drain",
    name: "Высасывание Бездны",
    kind: "spell",
    element: "void",
    manaCost: 14,
    cooldown: 2,
    baseDamage: 20,
    scaling: { spellPower: 1.3 },
    targets: "enemy",
    description: "Наносит урон тенью и восстанавливает HP равное 40% урона.",
  },
  void_curse: {
    id: "void_curse",
    name: "Проклятие",
    kind: "debuff",
    element: "void",
    manaCost: 18,
    cooldown: 3,
    effects: [
      { id: "curse", duration: 3, potency: 0.2 },
      { id: "mark", duration: 3, potency: 0.15 },
    ],
    targets: "enemy",
    description: "Метка усиливает получаемый урон +15% на 3 хода.",
  },
  beast_slash: {
    id: "beast_slash",
    name: "Рассечение",
    kind: "attack",
    element: "physical",
    manaCost: 6,
    cooldown: 1,
    baseDamage: 12,
    scaling: { attack: 1.1 },
    effects: [{ id: "bleed", duration: 3, potency: 5 }],
    targets: "enemy",
    description: "Глубокий порез — кровотечение на 3 хода.",
  },
  rally_pet: {
    id: "rally_pet",
    name: "Клич звериного друга",
    kind: "buff",
    element: "physical",
    manaCost: 12,
    cooldown: 5,
    effects: [{ id: "haste", duration: 3, potency: 0.25 }],
    targets: "ally",
    description: "Питомец получает +25% скорости/урона на 3 хода.",
  },
  // ------ POTIONS / UTILITY ------
  lesser_heal: {
    id: "lesser_heal",
    name: "Слабое лечение",
    kind: "heal",
    element: "holy",
    manaCost: 10,
    cooldown: 3,
    baseDamage: 30,
    scaling: { spellPower: 0.8 },
    targets: "self",
  },

  // ------ ENEMY ------
  e_bite: {
    id: "e_bite",
    name: "Укус",
    kind: "attack",
    element: "physical",
    manaCost: 0,
    cooldown: 0,
    baseDamage: 8,
    scaling: { attack: 1.0 },
    targets: "enemy",
  },
  e_slam: {
    id: "e_slam",
    name: "Сокрушительный удар",
    kind: "attack",
    element: "physical",
    manaCost: 0,
    cooldown: 2,
    baseDamage: 16,
    scaling: { attack: 1.3 },
    targets: "enemy",
  },
  e_shadow_fang: {
    id: "e_shadow_fang",
    name: "Клык теней",
    kind: "spell",
    element: "void",
    manaCost: 0,
    cooldown: 3,
    baseDamage: 22,
    scaling: { spellPower: 1.2 },
    targets: "enemy",
    effects: [{ id: "curse", duration: 2, potency: 0.15 }],
  },
  e_frost_lance: {
    id: "e_frost_lance",
    name: "Копьё льда",
    kind: "spell",
    element: "frost",
    manaCost: 0,
    cooldown: 2,
    baseDamage: 18,
    scaling: { spellPower: 1.1 },
    targets: "enemy",
    effects: [{ id: "chill", duration: 2, potency: 0.3 }],
  },
  e_infernal_roar: {
    id: "e_infernal_roar",
    name: "Инфернальный рык",
    kind: "debuff",
    element: "fire",
    manaCost: 0,
    cooldown: 4,
    targets: "enemy",
    effects: [
      { id: "weakness", duration: 2, potency: 0.25 },
      { id: "burn", duration: 3, potency: 8 },
    ],
  },
  e_abyssal_gaze: {
    id: "e_abyssal_gaze",
    name: "Взор Бездны",
    kind: "debuff",
    element: "void",
    manaCost: 0,
    cooldown: 5,
    targets: "enemy",
    effects: [
      { id: "silence", duration: 1, potency: 1 },
      { id: "mark", duration: 3, potency: 0.4 },
    ],
  },

  // ======== EXTENDED PLAYER ABILITIES ========
  whirlwind: {
    id: "whirlwind",
    name: "Вихрь",
    kind: "attack",
    element: "physical",
    manaCost: 18,
    cooldown: 4,
    baseDamage: 30,
    scaling: { attack: 1.6 },
    targets: "enemy",
    aoe: true,
    description: "Мощная AoE атака.",
  },
  execute: {
    id: "execute",
    name: "Казнь",
    kind: "attack",
    element: "physical",
    manaCost: 14,
    cooldown: 3,
    baseDamage: 35,
    scaling: { attack: 1.8 },
    targets: "enemy",
    description: "Наносит 200% урона если HP цели ниже 25%.",
  },
  berserk: {
    id: "berserk",
    name: "Ярость",
    kind: "buff",
    element: "physical",
    manaCost: 20,
    cooldown: 6,
    effects: [{ id: "haste", duration: 4, potency: 0.5 }],
    targets: "self",
    description: "+50% скорость/урон на 4 хода, но +25% получаемый урон.",
  },
  heroic_strike: {
    id: "heroic_strike",
    name: "Героический удар",
    kind: "attack",
    element: "physical",
    manaCost: 10,
    cooldown: 2,
    baseDamage: 22,
    scaling: { attack: 1.5 },
    targets: "enemy",
    description: "Мощный удар с гарантированным попаданием.",
  },
  frost_nova: {
    id: "frost_nova",
    name: "Ледяная нова",
    kind: "spell",
    element: "frost",
    manaCost: 22,
    cooldown: 5,
    baseDamage: 28,
    scaling: { spellPower: 1.4 },
    targets: "enemy",
    aoe: true,
    effects: [{ id: "freeze", duration: 1, potency: 1 }],
    description: "Замораживает всех врагов на 1 ход.",
  },
  fireball: {
    id: "fireball",
    name: "Огненный шар",
    kind: "spell",
    element: "fire",
    manaCost: 20,
    cooldown: 2,
    baseDamage: 32,
    scaling: { spellPower: 1.5 },
    targets: "enemy",
    effects: [{ id: "burn", duration: 3, potency: 10 }],
    description: "Массивный шар огня, поджигает цель.",
  },
  chain_lightning: {
    id: "chain_lightning",
    name: "Цепная молния",
    kind: "spell",
    element: "shock",
    manaCost: 24,
    cooldown: 4,
    baseDamage: 26,
    scaling: { spellPower: 1.3 },
    targets: "enemy",
    aoe: true,
    effects: [{ id: "shock", duration: 2, potency: 0.1 }],
    description: "Цепится по врагам.",
  },
  meteor: {
    id: "meteor",
    name: "Метеор",
    kind: "spell",
    element: "fire",
    manaCost: 40,
    cooldown: 6,
    baseDamage: 80,
    scaling: { spellPower: 2.5 },
    targets: "enemy",
    aoe: true,
    description: "Чудовищный удар с небес.",
  },
  soul_rip: {
    id: "soul_rip",
    name: "Разрыв души",
    kind: "spell",
    element: "void",
    manaCost: 30,
    cooldown: 5,
    baseDamage: 60,
    scaling: { spellPower: 2.0 },
    targets: "enemy",
    description: "Высасывает 60% урона как HP.",
  },
  vengeance: {
    id: "vengeance",
    name: "Возмездие",
    kind: "attack",
    element: "holy",
    manaCost: 15,
    cooldown: 3,
    baseDamage: 28,
    scaling: { attack: 1.2, spellPower: 0.8 },
    targets: "enemy",
    description: "Священный удар — +50% урона по нежити.",
  },
  divine_shield: {
    id: "divine_shield",
    name: "Божественный щит",
    kind: "buff",
    element: "holy",
    manaCost: 25,
    cooldown: 7,
    effects: [{ id: "shield", duration: 3, potency: 0.6 }],
    targets: "self",
    description: "Поглощает 60% урона на 3 хода.",
  },
  poison_dart: {
    id: "poison_dart",
    name: "Ядовитый дротик",
    kind: "attack",
    element: "physical",
    manaCost: 8,
    cooldown: 2,
    baseDamage: 10,
    scaling: { attack: 0.8 },
    targets: "enemy",
    effects: [{ id: "poison", duration: 5, potency: 8 }],
    description: "Сильный яд на 5 ходов.",
  },
  shadow_step: {
    id: "shadow_step",
    name: "Теневой шаг",
    kind: "buff",
    element: "void",
    manaCost: 12,
    cooldown: 4,
    effects: [{ id: "haste", duration: 2, potency: 0.4 }],
    targets: "self",
    description: "+40% уклонение на 2 хода.",
  },
  assassinate: {
    id: "assassinate",
    name: "Убийство",
    kind: "attack",
    element: "physical",
    manaCost: 18,
    cooldown: 4,
    baseDamage: 45,
    scaling: { attack: 2.2 },
    targets: "enemy",
    description: "Мощный критический удар.",
  },
  greater_heal: {
    id: "greater_heal",
    name: "Большое лечение",
    kind: "heal",
    element: "holy",
    manaCost: 20,
    cooldown: 4,
    baseDamage: 80,
    scaling: { spellPower: 1.2 },
    targets: "self",
    description: "Лечит на 80 + 120% магии.",
  },
  taunt: {
    id: "taunt",
    name: "Провокация",
    kind: "debuff",
    element: "physical",
    manaCost: 8,
    cooldown: 3,
    targets: "enemy",
    effects: [{ id: "weakness", duration: 2, potency: 0.3 }],
    description: "Цель получает -30% урона и атакует только Вас.",
  },
  mark_of_death: {
    id: "mark_of_death",
    name: "Метка смерти",
    kind: "debuff",
    element: "void",
    manaCost: 16,
    cooldown: 5,
    targets: "enemy",
    effects: [{ id: "mark", duration: 4, potency: 0.3 }],
    description: "Цель получает +30% урона на 4 хода.",
  },
  blood_rite: {
    id: "blood_rite",
    name: "Кровавый обряд",
    kind: "attack",
    element: "void",
    manaCost: 0,
    cooldown: 3,
    baseDamage: 40,
    scaling: { attack: 1.6, spellPower: 0.8 },
    targets: "enemy",
    description: "Забирает 20% вашего HP, наносит дикий урон.",
  },
  arcane_missiles: {
    id: "arcane_missiles",
    name: "Магические стрелы",
    kind: "spell",
    element: "shock",
    manaCost: 16,
    cooldown: 2,
    baseDamage: 12,
    scaling: { spellPower: 0.8 },
    targets: "enemy",
    description: "3 стрелы по 12 + 80% магии.",
  },
  abyss_reap: {
    id: "abyss_reap",
    name: "Жатва Бездны",
    kind: "attack",
    element: "void",
    manaCost: 35,
    cooldown: 7,
    baseDamage: 120,
    scaling: { attack: 2.0, spellPower: 1.5 },
    targets: "enemy",
    aoe: true,
    description: "Финальная техника Жнеца Бездны.",
  },
};
