import type { BossDef, DerivedStats, ElementId } from "@ton-abyss/shared";
import { ELEMENTS } from "@ton-abyss/shared";

function mkStats(o: Partial<DerivedStats> & { maxHp: number }): DerivedStats {
  const resistance = {} as Record<ElementId, number>;
  for (const el of ELEMENTS) resistance[el] = o.resistance?.[el] ?? 0;
  return {
    maxHp: o.maxHp,
    maxMana: o.maxMana ?? 200,
    attack: o.attack ?? 0,
    spellPower: o.spellPower ?? 0,
    defense: o.defense ?? 0,
    resistance,
    critChance: o.critChance ?? 0.1,
    critMultiplier: o.critMultiplier ?? 1.75,
    dodge: o.dodge ?? 0.04,
    accuracy: o.accuracy ?? 0.95,
    blockChance: o.blockChance ?? 0.1,
    blockAmount: o.blockAmount ?? 10,
    lifesteal: o.lifesteal ?? 0,
    speed: o.speed ?? 12,
    luck: 0,
  };
}

export const BOSSES: Record<string, BossDef> = {
  boss_crypt_lord: {
    id: "boss_crypt_lord",
    name: "Лорд склепа",
    archetype: "boss",
    level: 8,
    element: "void",
    stats: mkStats({
      maxHp: 1200,
      attack: 38,
      spellPower: 40,
      defense: 22,
      resistance: { physical: 0.1, fire: 0, frost: 0, shock: 0, void: 0.3, holy: -0.3 },
    }),
    abilities: ["e_slam", "e_shadow_fang"],
    lootTable: "lt_boss_crypt",
    xp: 900,
    gold: [180, 320],
    biome: "crypt",
    aiProfile: "tactician",
    phases: [
      {
        hpThreshold: 0.6,
        addAbilities: ["e_abyssal_gaze"],
        buff: { attack: 10, critChance: 0.05 },
      },
      {
        hpThreshold: 0.25,
        addAbilities: ["e_infernal_roar"],
        buff: { attack: 18, speed: 6, critChance: 0.1 },
      },
    ],
    enrageTurn: 25,
    uniqueDrops: ["off_kite_shield", "wpn_crypt_dagger", "egg_shade"],
  },
  boss_ice_matriarch: {
    id: "boss_ice_matriarch",
    name: "Матриарх льда",
    archetype: "boss",
    level: 16,
    element: "frost",
    stats: mkStats({
      maxHp: 3200,
      attack: 60,
      spellPower: 72,
      defense: 44,
      resistance: { physical: 0.1, fire: -0.25, frost: 0.6, shock: 0, void: 0, holy: 0 },
    }),
    abilities: ["e_frost_lance", "e_slam"],
    lootTable: "lt_boss_ice",
    xp: 2400,
    gold: [520, 880],
    biome: "ice",
    aiProfile: "spellweaver",
    phases: [
      { hpThreshold: 0.55, addAbilities: ["e_abyssal_gaze"], buff: { spellPower: 20 } },
      { hpThreshold: 0.2, addAbilities: ["e_infernal_roar"], buff: { spellPower: 40, speed: 8 } },
    ],
    uniqueDrops: ["arm_plate_legs", "wpn_tempest_bow"],
  },
  boss_infernal_prince: {
    id: "boss_infernal_prince",
    name: "Принц Преисподней",
    archetype: "boss",
    level: 22,
    element: "fire",
    stats: mkStats({
      maxHp: 6400,
      attack: 95,
      spellPower: 110,
      defense: 66,
      resistance: { physical: 0.1, fire: 0.7, frost: -0.3, shock: 0, void: 0.1, holy: -0.2 },
    }),
    abilities: ["e_infernal_roar", "e_slam"],
    lootTable: "lt_boss_infernal",
    xp: 6200,
    gold: [1400, 2400],
    biome: "infernal",
    phases: [
      { hpThreshold: 0.5, addAbilities: ["e_shadow_fang"], buff: { attack: 25 } },
      { hpThreshold: 0.15, addAbilities: ["e_abyssal_gaze"], buff: { attack: 45, spellPower: 40 } },
    ],
    uniqueDrops: ["wpn_abyssal_edge", "off_abyss_orb"],
  },
  boss_abyss_titan: {
    id: "boss_abyss_titan",
    name: "Титан Бездны",
    archetype: "apex",
    level: 35,
    element: "void",
    stats: mkStats({
      maxHp: 22000,
      attack: 180,
      spellPower: 200,
      defense: 140,
      resistance: { physical: 0.25, fire: 0, frost: 0, shock: 0, void: 0.75, holy: -0.4 },
    }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_boss_apex",
    xp: 28000,
    gold: [6000, 9000],
    biome: "abyss",
    phases: [
      { hpThreshold: 0.7, addAbilities: ["e_infernal_roar"], buff: { attack: 40 } },
      { hpThreshold: 0.35, addAbilities: ["e_frost_lance"], buff: { speed: 10, critChance: 0.15 } },
      { hpThreshold: 0.1, addAbilities: [], buff: { attack: 80, spellPower: 80, critMultiplier: 0.5 } },
    ],
    enrageTurn: 40,
    uniqueDrops: ["wpn_abyssal_edge", "arm_abyss_crown", "arm_abyss_raiment", "tr_abyss_sigil"],
  },

  boss_chapel_archon: {
    id: "boss_chapel_archon",
    name: "Падший архонт",
    archetype: "boss",
    level: 6,
    element: "holy",
    stats: mkStats({
      maxHp: 780,
      attack: 26,
      spellPower: 34,
      defense: 14,
      resistance: { physical: 0.05, fire: 0, frost: 0, shock: 0, void: -0.3, holy: 0.5 },
    }),
    abilities: ["e_slam", "e_shadow_fang"],
    lootTable: "lt_crypt_mid",
    xp: 520,
    gold: [100, 200],
    biome: "holy",
    phases: [
      { hpThreshold: 0.5, addAbilities: ["e_infernal_roar"], buff: { spellPower: 12 } },
    ],
    uniqueDrops: ["off_wooden_shield", "tr_copper_ring", "con_elixir_of_focus"],
  },
  boss_sunken_leviathan: {
    id: "boss_sunken_leviathan",
    name: "Затопленный левиафан",
    archetype: "boss",
    level: 10,
    element: "frost",
    stats: mkStats({
      maxHp: 1800,
      attack: 44,
      spellPower: 50,
      defense: 26,
      resistance: { physical: 0.15, fire: -0.3, frost: 0.55, shock: -0.25, void: 0, holy: 0 },
    }),
    abilities: ["e_frost_lance", "e_slam"],
    lootTable: "lt_ice_mid",
    xp: 1600,
    gold: [240, 440],
    biome: "water",
    phases: [
      { hpThreshold: 0.45, addAbilities: ["e_abyssal_gaze"], buff: { spellPower: 20 } },
    ],
    uniqueDrops: ["wpn_wand_of_frost", "off_focus_crystal"],
  },
  boss_glacier_monarch: {
    id: "boss_glacier_monarch",
    name: "Монарх ледника",
    archetype: "boss",
    level: 14,
    element: "frost",
    stats: mkStats({
      maxHp: 2600,
      attack: 56,
      spellPower: 64,
      defense: 36,
      resistance: { physical: 0.15, fire: -0.35, frost: 0.6, shock: 0, void: 0, holy: 0 },
    }),
    abilities: ["e_frost_lance", "e_slam", "e_infernal_roar"],
    lootTable: "lt_ice_high",
    xp: 2100,
    gold: [400, 700],
    biome: "ice",
    phases: [
      { hpThreshold: 0.5, addAbilities: ["e_shadow_fang"], buff: { attack: 14 } },
      { hpThreshold: 0.2, addAbilities: ["e_abyssal_gaze"], buff: { speed: 8, spellPower: 25 } },
    ],
    uniqueDrops: ["arm_dragon_mail", "wpn_frost_mace"],
  },
  boss_frostfell_hag: {
    id: "boss_frostfell_hag",
    name: "Ведьма морозной падали",
    archetype: "boss",
    level: 18,
    element: "void",
    stats: mkStats({
      maxHp: 3400,
      spellPower: 90,
      defense: 28,
      dodge: 0.16,
      resistance: { physical: 0.05, fire: -0.1, frost: 0.4, shock: 0, void: 0.4, holy: -0.3 },
    }),
    abilities: ["e_shadow_fang", "e_frost_lance", "e_abyssal_gaze"],
    lootTable: "lt_ice_high",
    xp: 3200,
    gold: [600, 1100],
    biome: "ice",
    phases: [
      { hpThreshold: 0.6, addAbilities: ["e_infernal_roar"], buff: { spellPower: 28 } },
      { hpThreshold: 0.25, addAbilities: ["e_slam"], buff: { dodge: 0.1, speed: 10 } },
    ],
    uniqueDrops: ["wpn_wand_of_shadow", "tr_amulet_of_frost"],
  },
  boss_molten_lord: {
    id: "boss_molten_lord",
    name: "Магменный владыка",
    archetype: "boss",
    level: 24,
    element: "fire",
    stats: mkStats({
      maxHp: 7800,
      attack: 106,
      spellPower: 124,
      defense: 72,
      resistance: { physical: 0.15, fire: 0.75, frost: -0.4, shock: 0, void: 0, holy: -0.2 },
    }),
    abilities: ["e_infernal_roar", "e_slam"],
    lootTable: "lt_infernal_mid",
    xp: 7800,
    gold: [1800, 3200],
    biome: "infernal",
    phases: [
      { hpThreshold: 0.5, addAbilities: ["e_shadow_fang"], buff: { attack: 30 } },
      { hpThreshold: 0.15, addAbilities: ["e_abyssal_gaze"], buff: { spellPower: 50, speed: 10 } },
    ],
    uniqueDrops: ["wpn_holy_hammer", "arm_dragon_mail"],
  },
  boss_ashen_vizier: {
    id: "boss_ashen_vizier",
    name: "Пепельный визирь",
    archetype: "boss",
    level: 26,
    element: "fire",
    stats: mkStats({
      maxHp: 9400,
      spellPower: 180,
      defense: 60,
      dodge: 0.14,
      resistance: { physical: 0.1, fire: 0.65, frost: -0.3, shock: 0, void: 0.2, holy: -0.2 },
    }),
    abilities: ["e_infernal_roar", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_infernal_mid",
    xp: 9800,
    gold: [2200, 4000],
    biome: "infernal",
    phases: [
      { hpThreshold: 0.5, addAbilities: ["e_frost_lance"], buff: { spellPower: 40 } },
      { hpThreshold: 0.15, addAbilities: ["e_slam"], buff: { spellPower: 80 } },
    ],
    uniqueDrops: ["wpn_ember_bow", "tr_amulet_of_flame"],
  },
  boss_void_herald: {
    id: "boss_void_herald",
    name: "Вестник пустоты",
    archetype: "boss",
    level: 32,
    element: "void",
    stats: mkStats({
      maxHp: 14000,
      attack: 146,
      spellPower: 180,
      defense: 96,
      resistance: { physical: 0.15, fire: 0, frost: 0, shock: 0, void: 0.7, holy: -0.45 },
    }),
    abilities: ["e_shadow_fang", "e_abyssal_gaze", "e_slam"],
    lootTable: "lt_abyss_mid",
    xp: 16800,
    gold: [3600, 6400],
    biome: "abyss",
    phases: [
      { hpThreshold: 0.5, addAbilities: ["e_infernal_roar"], buff: { attack: 40 } },
      { hpThreshold: 0.2, addAbilities: ["e_frost_lance"], buff: { spellPower: 60, speed: 8 } },
    ],
    uniqueDrops: ["wpn_void_tome", "off_abyss_orb", "tr_amulet_of_shadow"],
  },
  boss_forgotten_king: {
    id: "boss_forgotten_king",
    name: "Забытый король",
    archetype: "boss",
    level: 38,
    element: "void",
    stats: mkStats({
      maxHp: 19000,
      attack: 180,
      spellPower: 200,
      defense: 120,
      critChance: 0.15,
      resistance: { physical: 0.2, fire: 0, frost: 0, shock: 0, void: 0.7, holy: -0.45 },
    }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_high",
    xp: 24000,
    gold: [5400, 9200],
    biome: "abyss",
    phases: [
      { hpThreshold: 0.55, addAbilities: ["e_infernal_roar"], buff: { attack: 50 } },
      { hpThreshold: 0.22, addAbilities: ["e_frost_lance"], buff: { spellPower: 80 } },
      { hpThreshold: 0.08, addAbilities: [], buff: { attack: 100, critChance: 0.2 } },
    ],
    uniqueDrops: ["wpn_abyss_claws", "arm_abyss_raiment", "tr_ring_of_abyss"],
  },
};
