import type { DungeonDef } from "@ton-abyss/shared";

export const DUNGEON_MODIFIERS = [
  { id: "mod_bloodlust", name: "Жажда крови", description: "Монстры +30% урон, +30% лут.", effect: { monsterDamage: 1.3, lootQuantity: 1.3 } },
  { id: "mod_fortified", name: "Укреплено", description: "Монстры +50% HP, +15% качество лута.", effect: { monsterHp: 1.5, lootQuality: 1.15 } },
  { id: "mod_greed", name: "Алчность", description: "+60% золото, -15% качество лута.", effect: { goldFind: 1.6, lootQuality: 0.85 } },
  { id: "mod_apothecary", name: "Сухой", description: "Запрещены зелья.", effect: { forbidPotions: true, lootQuality: 1.1 } },
  { id: "mod_sudden_death", name: "Смертный марш", description: "Без продолжения после смерти. x1.4 лут.", effect: { suddenDeath: true, lootQuantity: 1.4 } },
];

export const DUNGEONS: Record<string, DungeonDef> = {
  dng_crypt_01: {
    id: "dng_crypt_01",
    name: "Заброшенный склеп",
    biome: "crypt",
    levelMin: 1,
    levelMax: 8,
    rooms: 6,
    bossId: "boss_crypt_lord",
    miniBossIds: ["m_ghoul"],
    monsterPool: ["m_crypt_rat", "m_crypt_skeleton", "m_ghoul", "m_wraith"],
    lootTable: "lt_crypt_mid",
    modifiers: [DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 50 },
    cooldownSeconds: 0,
    difficulty: 1,
  },
  dng_ice_01: {
    id: "dng_ice_01",
    name: "Ледяные пещеры",
    biome: "ice",
    levelMin: 9,
    levelMax: 18,
    rooms: 8,
    bossId: "boss_ice_matriarch",
    miniBossIds: ["m_yeti"],
    monsterPool: ["m_ice_wolf", "m_yeti", "m_wraith"],
    lootTable: "lt_ice_mid",
    modifiers: [DUNGEON_MODIFIERS[1]!],
    entryCost: { gold: 400 },
    cooldownSeconds: 600,
    difficulty: 2,
  },
  dng_infernal_01: {
    id: "dng_infernal_01",
    name: "Преисподняя",
    biome: "infernal",
    levelMin: 16,
    levelMax: 26,
    rooms: 10,
    bossId: "boss_infernal_prince",
    miniBossIds: ["m_hellhound"],
    monsterPool: ["m_imp", "m_hellhound"],
    lootTable: "lt_infernal_mid",
    modifiers: [DUNGEON_MODIFIERS[2]!, DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 2000 },
    cooldownSeconds: 1200,
    difficulty: 3,
  },
  dng_abyss_01: {
    id: "dng_abyss_01",
    name: "Врата Бездны",
    biome: "abyss",
    levelMin: 28,
    levelMax: 50,
    rooms: 14,
    bossId: "boss_abyss_titan",
    miniBossIds: ["m_abyss_crawler", "m_abyss_warden"],
    monsterPool: ["m_abyss_crawler", "m_abyss_warden", "m_wraith"],
    lootTable: "lt_abyss_high",
    modifiers: [DUNGEON_MODIFIERS[3]!, DUNGEON_MODIFIERS[4]!],
    entryCost: { gold: 10000, key: "key_abyss" },
    cooldownSeconds: 3600,
    difficulty: 6,
  },

  // ======== Act I extensions ========
  dng_chapel: {
    id: "dng_chapel",
    name: "Разрушенная часовня",
    biome: "holy",
    levelMin: 4,
    levelMax: 10,
    rooms: 7,
    bossId: "boss_chapel_archon",
    miniBossIds: ["m_zealot"],
    monsterPool: ["m_zealot", "m_paladin_fallen", "m_crypt_skeleton"],
    lootTable: "lt_crypt_mid",
    modifiers: [DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 180 },
    cooldownSeconds: 300,
    difficulty: 1,
  },
  dng_vault: {
    id: "dng_vault",
    name: "Затопленный склеп",
    biome: "water",
    levelMin: 6,
    levelMax: 12,
    rooms: 8,
    bossId: "boss_sunken_leviathan",
    miniBossIds: ["m_sea_wraith"],
    monsterPool: ["m_drowned", "m_sea_wraith", "m_crypt_spider", "m_crypt_revenant"],
    lootTable: "lt_crypt_mid",
    modifiers: [DUNGEON_MODIFIERS[1]!, DUNGEON_MODIFIERS[2]!],
    entryCost: { gold: 260 },
    cooldownSeconds: 300,
    difficulty: 2,
  },

  // ======== Act II extensions ========
  dng_glacier: {
    id: "dng_glacier",
    name: "Вершина ледника",
    biome: "ice",
    levelMin: 12,
    levelMax: 20,
    rooms: 9,
    bossId: "boss_glacier_monarch",
    miniBossIds: ["m_frost_giant"],
    monsterPool: ["m_ice_wolf", "m_yeti", "m_frost_giant"],
    lootTable: "lt_ice_high",
    modifiers: [DUNGEON_MODIFIERS[0]!, DUNGEON_MODIFIERS[2]!],
    entryCost: { gold: 1200 },
    cooldownSeconds: 900,
    difficulty: 2,
  },
  dng_frostfell: {
    id: "dng_frostfell",
    name: "Руины Морозной падали",
    biome: "ice",
    levelMin: 15,
    levelMax: 24,
    rooms: 10,
    bossId: "boss_frostfell_hag",
    miniBossIds: ["m_frost_witch", "m_tomb_knight"],
    monsterPool: ["m_frost_witch", "m_yeti", "m_wraith", "m_tomb_knight"],
    lootTable: "lt_ice_high",
    modifiers: [DUNGEON_MODIFIERS[1]!, DUNGEON_MODIFIERS[4]!],
    entryCost: { gold: 2800 },
    cooldownSeconds: 900,
    difficulty: 3,
  },

  // ======== Act III extensions ========
  dng_molten: {
    id: "dng_molten",
    name: "Раскалённые чертоги",
    biome: "infernal",
    levelMin: 20,
    levelMax: 28,
    rooms: 11,
    bossId: "boss_molten_lord",
    miniBossIds: ["m_fire_elemental", "m_inferno_brute"],
    monsterPool: ["m_imp", "m_hellhound", "m_fire_elemental", "m_inferno_brute"],
    lootTable: "lt_infernal_mid",
    modifiers: [DUNGEON_MODIFIERS[0]!, DUNGEON_MODIFIERS[1]!],
    entryCost: { gold: 5400 },
    cooldownSeconds: 1800,
    difficulty: 4,
  },
  dng_ashen: {
    id: "dng_ashen",
    name: "Пепельная пустошь",
    biome: "infernal",
    levelMin: 24,
    levelMax: 30,
    rooms: 12,
    bossId: "boss_ashen_vizier",
    miniBossIds: ["m_fire_elemental", "m_shadow_imp"],
    monsterPool: ["m_hellhound", "m_shadow_imp", "m_inferno_brute", "m_imp"],
    lootTable: "lt_infernal_mid",
    modifiers: [DUNGEON_MODIFIERS[2]!, DUNGEON_MODIFIERS[3]!],
    entryCost: { gold: 8800 },
    cooldownSeconds: 1800,
    difficulty: 5,
  },

  // ======== Act IV extensions ========
  dng_void_shrine: {
    id: "dng_void_shrine",
    name: "Храм Пустоты",
    biome: "abyss",
    levelMin: 30,
    levelMax: 38,
    rooms: 13,
    bossId: "boss_void_herald",
    miniBossIds: ["m_abyss_warden", "m_void_horror"],
    monsterPool: ["m_abyss_crawler", "m_shadow_imp", "m_void_horror", "m_deep_wraith"],
    lootTable: "lt_abyss_mid",
    modifiers: [DUNGEON_MODIFIERS[3]!, DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 14000, key: "key_abyss" },
    cooldownSeconds: 3600,
    difficulty: 5,
  },
  dng_depths: {
    id: "dng_depths",
    name: "Забытые глубины",
    biome: "abyss",
    levelMin: 34,
    levelMax: 42,
    rooms: 14,
    bossId: "boss_forgotten_king",
    miniBossIds: ["m_forgotten_one", "m_nightmare_crawler"],
    monsterPool: ["m_void_horror", "m_deep_wraith", "m_forgotten_one", "m_nightmare_crawler"],
    lootTable: "lt_abyss_high",
    modifiers: [DUNGEON_MODIFIERS[4]!, DUNGEON_MODIFIERS[3]!, DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 24000, key: "key_abyss" },
    cooldownSeconds: 5400,
    difficulty: 6,
  },
  dng_celestial_trial: {
    id: "dng_celestial_trial",
    name: "Небесное испытание",
    biome: "holy",
    levelMin: 45,
    levelMax: 60,
    rooms: 16,
    bossId: "boss_abyss_titan",
    miniBossIds: ["m_forgotten_one"],
    monsterPool: ["m_forgotten_one", "m_nightmare_crawler", "m_deep_wraith"],
    lootTable: "lt_abyss_high",
    modifiers: [DUNGEON_MODIFIERS[4]!, DUNGEON_MODIFIERS[3]!],
    entryCost: { gold: 80000, key: "key_celestial" },
    cooldownSeconds: 7200,
    difficulty: 7,
  },
};
