import type { DungeonDef } from "@ton-abyss/shared";

export const DUNGEON_MODIFIERS = [
  { id: "mod_bloodlust", name: "Жажда крови", description: "Монстры +30% урон, +30% лут.", effect: { monsterDamage: 1.3, lootQuantity: 1.3 } },
  { id: "mod_fortified", name: "Укреплено", description: "Монстры +50% HP, +15% качество лута.", effect: { monsterHp: 1.5, lootQuality: 1.15 } },
  { id: "mod_greed", name: "Алчность", description: "+60% золото, -15% качество лута.", effect: { goldFind: 1.6, lootQuality: 0.85 } },
  { id: "mod_apothecary", name: "Сухой", description: "Запрещены зелья.", effect: { forbidPotions: true, lootQuality: 1.1 } },
  { id: "mod_sudden_death", name: "Смертный марш", description: "Без продолжения после смерти. x1.4 лут.", effect: { suddenDeath: true, lootQuantity: 1.4 } },
];

export const DUNGEONS: Record<string, DungeonDef> = {
  dng_crypt_01: {
    id: "dng_crypt_01",
    name: "Заброшенный склеп",
    biome: "crypt",
    levelMin: 1,
    levelMax: 8,
    rooms: 6,
    bossId: "boss_crypt_lord",
    miniBossIds: ["m_ghoul"],
    monsterPool: ["m_crypt_rat", "m_crypt_skeleton", "m_ghoul", "m_wraith"],
    lootTable: "lt_crypt_mid",
    modifiers: [DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 50 },
    cooldownSeconds: 0,
    difficulty: 1,
  },
  dng_ice_01: {
    id: "dng_ice_01",
    name: "Ледяные пещеры",
    biome: "ice",
    levelMin: 9,
    levelMax: 18,
    rooms: 8,
    bossId: "boss_ice_matriarch",
    miniBossIds: ["m_yeti"],
    monsterPool: ["m_ice_wolf", "m_yeti", "m_wraith"],
    lootTable: "lt_ice_mid",
    modifiers: [DUNGEON_MODIFIERS[1]!],
    entryCost: { gold: 400 },
    cooldownSeconds: 600,
    difficulty: 2,
  },
  dng_infernal_01: {
    id: "dng_infernal_01",
    name: "Преисподняя",
    biome: "infernal",
    levelMin: 16,
    levelMax: 26,
    rooms: 10,
    bossId: "boss_infernal_prince",
    miniBossIds: ["m_hellhound"],
    monsterPool: ["m_imp", "m_hellhound"],
    lootTable: "lt_infernal_mid",
    modifiers: [DUNGEON_MODIFIERS[2]!, DUNGEON_MODIFIERS[0]!],
    entryCost: { gold: 2000 },
    cooldownSeconds: 1200,
    difficulty: 3,
  },
  dng_abyss_01: {
    id: "dng_abyss_01",
    name: "Врата Бездны",
    biome: "abyss",
    levelMin: 28,
    levelMax: 50,
    rooms: 14,
    bossId: "boss_abyss_titan",
    miniBossIds: ["m_abyss_crawler", "m_abyss_warden"],
    monsterPool: ["m_abyss_crawler", "m_abyss_warden", "m_wraith"],
    lootTable: "lt_abyss_high",
    modifiers: [DUNGEON_MODIFIERS[3]!, DUNGEON_MODIFIERS[4]!],
    entryCost: { gold: 10000, key: "key_abyss" },
    cooldownSeconds: 3600,
    difficulty: 6,
  },
};
