import type { LootTableDef } from "@ton-abyss/shared";

export const LOOT_TABLES: Record<string, LootTableDef> = {
  lt_crypt_low: {
    id: "lt_crypt_low",
    rolls: [1, 2],
    entries: [
      { kind: "gold", weight: 100, amount: [3, 10] },
      { kind: "material", baseId: "mat_linen", weight: 60, amount: [1, 2] },
      { kind: "material", baseId: "mat_leather", weight: 50, amount: [1, 2] },
      { kind: "item", baseId: "wpn_rusty_shortsword", weight: 6 },
      { kind: "item", baseId: "arm_leather_cap", weight: 6 },
      { kind: "item", baseId: "con_minor_hp_potion", weight: 12 },
      { kind: "item", baseId: "key_crypt", weight: 3 },
    ],
  },
  lt_crypt_mid: {
    id: "lt_crypt_mid",
    rolls: [1, 3],
    entries: [
      { kind: "gold", weight: 100, amount: [8, 22] },
      { kind: "material", baseId: "mat_iron", weight: 45, amount: [1, 3] },
      { kind: "material", baseId: "mat_leather", weight: 40, amount: [1, 3] },
      { kind: "item", baseId: "wpn_iron_sword", weight: 10 },
      { kind: "item", baseId: "arm_chainmail", weight: 8 },
      { kind: "item", baseId: "off_wooden_shield", weight: 8 },
      { kind: "item", baseId: "con_hp_potion", weight: 14 },
      { kind: "item", baseId: "rune_strength", weight: 3 },
    ],
  },
  lt_ice_mid: {
    id: "lt_ice_mid",
    rolls: [1, 3],
    entries: [
      { kind: "gold", weight: 100, amount: [16, 40] },
      { kind: "material", baseId: "mat_steel", weight: 40, amount: [1, 3] },
      { kind: "item", baseId: "wpn_steel_sword", weight: 9 },
      { kind: "item", baseId: "wpn_warhammer", weight: 7 },
      { kind: "item", baseId: "arm_runed_helm", weight: 7 },
      { kind: "item", baseId: "off_kite_shield", weight: 7 },
      { kind: "item", baseId: "con_hp_potion", weight: 12 },
      { kind: "item", baseId: "rune_ward", weight: 5 },
    ],
  },
  lt_ice_high: {
    id: "lt_ice_high",
    rolls: [2, 4],
    entries: [
      { kind: "gold", weight: 100, amount: [30, 90] },
      { kind: "material", baseId: "mat_steel", weight: 45, amount: [2, 5] },
      { kind: "material", baseId: "mat_mithril", weight: 10, amount: [1, 2] },
      { kind: "item", baseId: "arm_platemail", weight: 10 },
      { kind: "item", baseId: "arm_plate_legs", weight: 9 },
      { kind: "item", baseId: "tr_amulet_of_dawn", weight: 6 },
      { kind: "item", baseId: "rune_flame", weight: 5 },
    ],
  },
  lt_infernal_mid: {
    id: "lt_infernal_mid",
    rolls: [2, 4],
    entries: [
      { kind: "gold", weight: 100, amount: [40, 120] },
      { kind: "material", baseId: "mat_steel", weight: 40, amount: [3, 6] },
      { kind: "material", baseId: "mat_phoenix_feather", weight: 10, amount: [1, 2] },
      { kind: "item", baseId: "wpn_arcane_staff", weight: 7 },
      { kind: "item", baseId: "arm_robe_of_runes", weight: 7 },
      { kind: "item", baseId: "tr_ring_of_vigor", weight: 6 },
      { kind: "item", baseId: "egg_wyrmling", weight: 1 },
    ],
  },
  lt_abyss_mid: {
    id: "lt_abyss_mid",
    rolls: [2, 4],
    entries: [
      { kind: "gold", weight: 100, amount: [90, 240] },
      { kind: "material", baseId: "mat_mithril", weight: 30, amount: [2, 5] },
      { kind: "material", baseId: "mat_void_silk", weight: 15, amount: [1, 3] },
      { kind: "material", baseId: "mat_abyss_shard", weight: 6, amount: [1, 2] },
      { kind: "item", baseId: "wpn_void_tome", weight: 4 },
      { kind: "item", baseId: "off_abyss_orb", weight: 4 },
      { kind: "item", baseId: "tr_abyss_sigil", weight: 2 },
    ],
  },
  lt_abyss_high: {
    id: "lt_abyss_high",
    rolls: [3, 5],
    entries: [
      { kind: "gold", weight: 100, amount: [200, 600] },
      { kind: "material", baseId: "mat_mithril", weight: 30, amount: [3, 7] },
      { kind: "material", baseId: "mat_adamant", weight: 8, amount: [1, 3] },
      { kind: "material", baseId: "mat_abyss_shard", weight: 14, amount: [1, 3] },
      { kind: "item", baseId: "wpn_abyssal_edge", weight: 2 },
      { kind: "item", baseId: "arm_abyss_crown", weight: 2 },
      { kind: "item", baseId: "arm_abyss_raiment", weight: 2 },
      { kind: "item", baseId: "tr_abyss_sigil", weight: 3 },
      { kind: "item", baseId: "egg_shade", weight: 1 },
    ],
  },
  lt_boss_crypt: {
    id: "lt_boss_crypt",
    rolls: [3, 4],
    entries: [
      { kind: "gold", weight: 100, amount: [120, 280] },
      { kind: "material", baseId: "mat_boss_soul", weight: 60, amount: [1, 1] },
      { kind: "item", baseId: "off_kite_shield", weight: 30, rarityOverride: { rare: 60, epic: 30, legendary: 8, mythic: 1.5, abyssal: 0.1 } },
      { kind: "item", baseId: "wpn_crypt_dagger", weight: 30, rarityOverride: { rare: 60, epic: 30, legendary: 8, mythic: 1.5, abyssal: 0.1 } },
      { kind: "item", baseId: "egg_shade", weight: 6 },
    ],
  },
  lt_boss_ice: {
    id: "lt_boss_ice",
    rolls: [3, 5],
    entries: [
      { kind: "gold", weight: 100, amount: [400, 900] },
      { kind: "material", baseId: "mat_boss_soul", weight: 60, amount: [1, 2] },
      { kind: "item", baseId: "arm_plate_legs", weight: 25, rarityOverride: { rare: 55, epic: 35, legendary: 9, mythic: 1.5, abyssal: 0.1 } },
      { kind: "item", baseId: "wpn_tempest_bow", weight: 22, rarityOverride: { rare: 55, epic: 35, legendary: 9, mythic: 1.5, abyssal: 0.1 } },
    ],
  },
  lt_boss_infernal: {
    id: "lt_boss_infernal",
    rolls: [4, 6],
    entries: [
      { kind: "gold", weight: 100, amount: [1000, 2600] },
      { kind: "material", baseId: "mat_boss_soul", weight: 60, amount: [2, 3] },
      { kind: "material", baseId: "mat_phoenix_feather", weight: 30, amount: [1, 2] },
      { kind: "item", baseId: "wpn_abyssal_edge", weight: 10, rarityOverride: { rare: 40, epic: 40, legendary: 15, mythic: 4, abyssal: 0.3 } },
      { kind: "item", baseId: "off_abyss_orb", weight: 18, rarityOverride: { rare: 40, epic: 40, legendary: 15, mythic: 4, abyssal: 0.3 } },
    ],
  },
  lt_boss_apex: {
    id: "lt_boss_apex",
    rolls: [5, 7],
    entries: [
      { kind: "gold", weight: 100, amount: [5000, 12000] },
      { kind: "material", baseId: "mat_boss_soul", weight: 80, amount: [4, 6] },
      { kind: "material", baseId: "mat_abyss_shard", weight: 60, amount: [2, 5] },
      { kind: "material", baseId: "mat_adamant", weight: 30, amount: [1, 3] },
      { kind: "item", baseId: "wpn_abyssal_edge", weight: 14, rarityOverride: { epic: 40, legendary: 35, mythic: 10, abyssal: 1 } },
      { kind: "item", baseId: "arm_abyss_crown", weight: 14, rarityOverride: { epic: 40, legendary: 35, mythic: 10, abyssal: 1 } },
      { kind: "item", baseId: "arm_abyss_raiment", weight: 14, rarityOverride: { epic: 40, legendary: 35, mythic: 10, abyssal: 1 } },
      { kind: "item", baseId: "tr_abyss_sigil", weight: 18, rarityOverride: { epic: 40, legendary: 35, mythic: 10, abyssal: 1 } },
    ],
  },
};
