import type { MonsterDef, DerivedStats, ElementId } from "@ton-abyss/shared";
import { ELEMENTS } from "@ton-abyss/shared";

function mkStats(opts: Partial<DerivedStats> & { maxHp: number; attack?: number; spellPower?: number; defense?: number }): DerivedStats {
  const resistance = {} as Record<ElementId, number>;
  for (const el of ELEMENTS) resistance[el] = opts.resistance?.[el] ?? 0;
  return {
    maxHp: opts.maxHp,
    maxMana: opts.maxMana ?? 30,
    attack: opts.attack ?? 0,
    spellPower: opts.spellPower ?? 0,
    defense: opts.defense ?? 0,
    resistance,
    critChance: opts.critChance ?? 0.05,
    critMultiplier: opts.critMultiplier ?? 1.5,
    dodge: opts.dodge ?? 0.02,
    accuracy: opts.accuracy ?? 0.9,
    blockChance: opts.blockChance ?? 0,
    blockAmount: opts.blockAmount ?? 0,
    lifesteal: opts.lifesteal ?? 0,
    speed: opts.speed ?? 10,
    luck: 0,
  };
}

export const MONSTERS: Record<string, MonsterDef> = {
  // Biome: Crypt
  m_crypt_rat: {
    id: "m_crypt_rat",
    name: "Склеповая крыса",
    archetype: "grunt",
    level: 1,
    element: "physical",
    stats: mkStats({ maxHp: 35, attack: 6, defense: 2, speed: 12 }),
    abilities: ["e_bite"],
    lootTable: "lt_crypt_low",
    xp: 14,
    gold: [2, 8],
    biome: "crypt",
    aiProfile: "aggressive",
  },
  m_crypt_skeleton: {
    id: "m_crypt_skeleton",
    name: "Костяной скелет",
    archetype: "grunt",
    level: 3,
    element: "physical",
    stats: mkStats({ maxHp: 60, attack: 10, defense: 5, speed: 9 }),
    abilities: ["e_bite", "e_slam"],
    lootTable: "lt_crypt_low",
    xp: 26,
    gold: [4, 12],
    biome: "crypt",
  },
  m_ghoul: {
    id: "m_ghoul",
    name: "Упырь",
    archetype: "brute",
    level: 6,
    element: "void",
    stats: mkStats({ maxHp: 120, attack: 16, defense: 9, resistance: { physical: 0, fire: -0.1, frost: 0, shock: 0, void: 0.2, holy: -0.25 } }),
    abilities: ["e_bite", "e_slam", "e_shadow_fang"],
    lootTable: "lt_crypt_mid",
    xp: 58,
    gold: [10, 22],
    biome: "crypt",
    aiProfile: "aggressive",
  },
  m_wraith: {
    id: "m_wraith",
    name: "Призрак",
    archetype: "caster",
    level: 8,
    element: "void",
    stats: mkStats({ maxHp: 95, spellPower: 24, defense: 4, dodge: 0.12, resistance: { physical: 0.25, fire: 0, frost: 0, shock: 0, void: 0.3, holy: -0.35 } }),
    abilities: ["e_shadow_fang", "e_frost_lance"],
    lootTable: "lt_crypt_mid",
    xp: 90,
    gold: [14, 28],
    biome: "crypt",
    aiProfile: "spellweaver",
  },
  // Biome: Ice Caverns
  m_ice_wolf: {
    id: "m_ice_wolf",
    name: "Ледяной волк",
    archetype: "skirmisher",
    level: 10,
    element: "frost",
    stats: mkStats({ maxHp: 150, attack: 22, defense: 8, speed: 15, resistance: { physical: 0, fire: -0.25, frost: 0.5, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_bite", "e_frost_lance"],
    lootTable: "lt_ice_mid",
    xp: 120,
    gold: [18, 34],
    biome: "ice",
  },
  m_yeti: {
    id: "m_yeti",
    name: "Йети",
    archetype: "brute",
    level: 14,
    element: "frost",
    stats: mkStats({ maxHp: 320, attack: 34, defense: 18, resistance: { physical: 0.1, fire: -0.35, frost: 0.5, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_slam", "e_frost_lance"],
    lootTable: "lt_ice_high",
    xp: 280,
    gold: [28, 50],
    biome: "ice",
  },
  // Biome: Infernal
  m_imp: {
    id: "m_imp",
    name: "Бесёнок",
    archetype: "caster",
    level: 12,
    element: "fire",
    stats: mkStats({ maxHp: 170, spellPower: 30, defense: 6, resistance: { physical: 0, fire: 0.5, frost: -0.25, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_shadow_fang", "e_infernal_roar"],
    lootTable: "lt_infernal_mid",
    xp: 160,
    gold: [22, 40],
    biome: "infernal",
  },
  m_hellhound: {
    id: "m_hellhound",
    name: "Адская гончая",
    archetype: "skirmisher",
    level: 16,
    element: "fire",
    stats: mkStats({ maxHp: 280, attack: 42, defense: 14, speed: 14, resistance: { physical: 0, fire: 0.6, frost: -0.3, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_bite", "e_infernal_roar"],
    lootTable: "lt_infernal_mid",
    xp: 320,
    gold: [34, 58],
    biome: "infernal",
  },
  // Biome: Abyss
  m_abyss_crawler: {
    id: "m_abyss_crawler",
    name: "Ползун Бездны",
    archetype: "elite",
    level: 22,
    element: "void",
    stats: mkStats({ maxHp: 520, attack: 62, defense: 26, resistance: { physical: 0.1, fire: 0, frost: 0, shock: 0, void: 0.5, holy: -0.4 } }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_mid",
    xp: 880,
    gold: [60, 100],
    biome: "abyss",
  },
  m_abyss_warden: {
    id: "m_abyss_warden",
    name: "Страж Бездны",
    archetype: "elite",
    level: 28,
    element: "void",
    stats: mkStats({ maxHp: 780, attack: 88, defense: 44, resistance: { physical: 0.2, fire: 0, frost: 0, shock: 0, void: 0.6, holy: -0.4 } }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_high",
    xp: 1400,
    gold: [90, 160],
    biome: "abyss",
  },
};
