import type { MonsterDef, DerivedStats, ElementId } from "@ton-abyss/shared";
import { ELEMENTS } from "@ton-abyss/shared";

function mkStats(opts: Partial<DerivedStats> & { maxHp: number; attack?: number; spellPower?: number; defense?: number }): DerivedStats {
  const resistance = {} as Record<ElementId, number>;
  for (const el of ELEMENTS) resistance[el] = opts.resistance?.[el] ?? 0;
  return {
    maxHp: opts.maxHp,
    maxMana: opts.maxMana ?? 30,
    attack: opts.attack ?? 0,
    spellPower: opts.spellPower ?? 0,
    defense: opts.defense ?? 0,
    resistance,
    critChance: opts.critChance ?? 0.05,
    critMultiplier: opts.critMultiplier ?? 1.5,
    dodge: opts.dodge ?? 0.02,
    accuracy: opts.accuracy ?? 0.9,
    blockChance: opts.blockChance ?? 0,
    blockAmount: opts.blockAmount ?? 0,
    lifesteal: opts.lifesteal ?? 0,
    speed: opts.speed ?? 10,
    luck: 0,
  };
}

export const MONSTERS: Record<string, MonsterDef> = {
  // Biome: Crypt
  m_crypt_rat: {
    id: "m_crypt_rat",
    name: "Склеповая крыса",
    archetype: "grunt",
    level: 1,
    element: "physical",
    stats: mkStats({ maxHp: 35, attack: 6, defense: 2, speed: 12 }),
    abilities: ["e_bite"],
    lootTable: "lt_crypt_low",
    xp: 14,
    gold: [2, 8],
    biome: "crypt",
    aiProfile: "aggressive",
  },
  m_crypt_skeleton: {
    id: "m_crypt_skeleton",
    name: "Костяной скелет",
    archetype: "grunt",
    level: 3,
    element: "physical",
    stats: mkStats({ maxHp: 60, attack: 10, defense: 5, speed: 9 }),
    abilities: ["e_bite", "e_slam"],
    lootTable: "lt_crypt_low",
    xp: 26,
    gold: [4, 12],
    biome: "crypt",
  },
  m_ghoul: {
    id: "m_ghoul",
    name: "Упырь",
    archetype: "brute",
    level: 6,
    element: "void",
    stats: mkStats({ maxHp: 120, attack: 16, defense: 9, resistance: { physical: 0, fire: -0.1, frost: 0, shock: 0, void: 0.2, holy: -0.25 } }),
    abilities: ["e_bite", "e_slam", "e_shadow_fang"],
    lootTable: "lt_crypt_mid",
    xp: 58,
    gold: [10, 22],
    biome: "crypt",
    aiProfile: "aggressive",
  },
  m_wraith: {
    id: "m_wraith",
    name: "Призрак",
    archetype: "caster",
    level: 8,
    element: "void",
    stats: mkStats({ maxHp: 95, spellPower: 24, defense: 4, dodge: 0.12, resistance: { physical: 0.25, fire: 0, frost: 0, shock: 0, void: 0.3, holy: -0.35 } }),
    abilities: ["e_shadow_fang", "e_frost_lance"],
    lootTable: "lt_crypt_mid",
    xp: 90,
    gold: [14, 28],
    biome: "crypt",
    aiProfile: "spellweaver",
  },
  // Biome: Ice Caverns
  m_ice_wolf: {
    id: "m_ice_wolf",
    name: "Ледяной волк",
    archetype: "skirmisher",
    level: 10,
    element: "frost",
    stats: mkStats({ maxHp: 150, attack: 22, defense: 8, speed: 15, resistance: { physical: 0, fire: -0.25, frost: 0.5, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_bite", "e_frost_lance"],
    lootTable: "lt_ice_mid",
    xp: 120,
    gold: [18, 34],
    biome: "ice",
  },
  m_yeti: {
    id: "m_yeti",
    name: "Йети",
    archetype: "brute",
    level: 14,
    element: "frost",
    stats: mkStats({ maxHp: 320, attack: 34, defense: 18, resistance: { physical: 0.1, fire: -0.35, frost: 0.5, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_slam", "e_frost_lance"],
    lootTable: "lt_ice_high",
    xp: 280,
    gold: [28, 50],
    biome: "ice",
  },
  // Biome: Infernal
  m_imp: {
    id: "m_imp",
    name: "Бесёнок",
    archetype: "caster",
    level: 12,
    element: "fire",
    stats: mkStats({ maxHp: 170, spellPower: 30, defense: 6, resistance: { physical: 0, fire: 0.5, frost: -0.25, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_shadow_fang", "e_infernal_roar"],
    lootTable: "lt_infernal_mid",
    xp: 160,
    gold: [22, 40],
    biome: "infernal",
  },
  m_hellhound: {
    id: "m_hellhound",
    name: "Адская гончая",
    archetype: "skirmisher",
    level: 16,
    element: "fire",
    stats: mkStats({ maxHp: 280, attack: 42, defense: 14, speed: 14, resistance: { physical: 0, fire: 0.6, frost: -0.3, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_bite", "e_infernal_roar"],
    lootTable: "lt_infernal_mid",
    xp: 320,
    gold: [34, 58],
    biome: "infernal",
  },
  // Biome: Abyss
  m_abyss_crawler: {
    id: "m_abyss_crawler",
    name: "Ползун Бездны",
    archetype: "elite",
    level: 22,
    element: "void",
    stats: mkStats({ maxHp: 520, attack: 62, defense: 26, resistance: { physical: 0.1, fire: 0, frost: 0, shock: 0, void: 0.5, holy: -0.4 } }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_mid",
    xp: 880,
    gold: [60, 100],
    biome: "abyss",
  },
  m_abyss_warden: {
    id: "m_abyss_warden",
    name: "Страж Бездны",
    archetype: "elite",
    level: 28,
    element: "void",
    stats: mkStats({ maxHp: 780, attack: 88, defense: 44, resistance: { physical: 0.2, fire: 0, frost: 0, shock: 0, void: 0.6, holy: -0.4 } }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_high",
    xp: 1400,
    gold: [90, 160],
    biome: "abyss",
  },

  // Biome: Crypt (extra)
  m_crypt_spider: {
    id: "m_crypt_spider",
    name: "Склеповой паук",
    archetype: "skirmisher",
    level: 4,
    element: "physical",
    stats: mkStats({ maxHp: 65, attack: 12, defense: 3, speed: 13, critChance: 0.08 }),
    abilities: ["e_bite"],
    lootTable: "lt_crypt_low",
    xp: 35,
    gold: [6, 14],
    biome: "crypt",
    aiProfile: "aggressive",
  },
  m_crypt_revenant: {
    id: "m_crypt_revenant",
    name: "Мстительный дух",
    archetype: "caster",
    level: 7,
    element: "void",
    stats: mkStats({ maxHp: 85, spellPower: 18, defense: 3, dodge: 0.1 }),
    abilities: ["e_shadow_fang"],
    lootTable: "lt_crypt_mid",
    xp: 70,
    gold: [12, 22],
    biome: "crypt",
    aiProfile: "spellweaver",
  },
  m_tomb_knight: {
    id: "m_tomb_knight",
    name: "Рыцарь гробницы",
    archetype: "elite",
    level: 9,
    element: "physical",
    stats: mkStats({ maxHp: 220, attack: 28, defense: 22 }),
    abilities: ["e_slam", "e_bite"],
    lootTable: "lt_crypt_mid",
    xp: 180,
    gold: [28, 48],
    biome: "crypt",
  },

  // Biome: Chapel (holy)
  m_zealot: {
    id: "m_zealot",
    name: "Безумный фанатик",
    archetype: "grunt",
    level: 5,
    element: "holy",
    stats: mkStats({ maxHp: 75, attack: 14, defense: 6, resistance: { physical: 0, fire: 0, frost: 0, shock: 0, void: -0.25, holy: 0.35 } }),
    abilities: ["e_bite", "e_slam"],
    lootTable: "lt_crypt_mid",
    xp: 55,
    gold: [8, 18],
    biome: "holy",
  },
  m_paladin_fallen: {
    id: "m_paladin_fallen",
    name: "Падший паладин",
    archetype: "brute",
    level: 10,
    element: "holy",
    stats: mkStats({ maxHp: 250, attack: 32, defense: 24, blockChance: 0.12, resistance: { physical: 0.1, fire: 0, frost: 0, shock: 0, void: -0.25, holy: 0.4 } }),
    abilities: ["e_slam"],
    lootTable: "lt_ice_mid",
    xp: 220,
    gold: [32, 58],
    biome: "holy",
  },

  // Biome: Water (sunken)
  m_drowned: {
    id: "m_drowned",
    name: "Утопленник",
    archetype: "grunt",
    level: 6,
    element: "frost",
    stats: mkStats({ maxHp: 105, attack: 16, defense: 4, resistance: { physical: 0.1, fire: -0.3, frost: 0.4, shock: -0.2, void: 0, holy: 0 } }),
    abilities: ["e_bite"],
    lootTable: "lt_crypt_mid",
    xp: 65,
    gold: [10, 20],
    biome: "water",
  },
  m_sea_wraith: {
    id: "m_sea_wraith",
    name: "Морской призрак",
    archetype: "caster",
    level: 8,
    element: "frost",
    stats: mkStats({ maxHp: 135, spellPower: 26, defense: 6, dodge: 0.12 }),
    abilities: ["e_frost_lance", "e_shadow_fang"],
    lootTable: "lt_ice_mid",
    xp: 130,
    gold: [18, 34],
    biome: "water",
  },

  // Biome: Ice (extra)
  m_frost_giant: {
    id: "m_frost_giant",
    name: "Ледяной великан",
    archetype: "brute",
    level: 18,
    element: "frost",
    stats: mkStats({ maxHp: 520, attack: 52, defense: 28, resistance: { physical: 0.15, fire: -0.4, frost: 0.55, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_slam", "e_frost_lance"],
    lootTable: "lt_ice_high",
    xp: 560,
    gold: [48, 90],
    biome: "ice",
  },
  m_frost_witch: {
    id: "m_frost_witch",
    name: "Ведьма льда",
    archetype: "caster",
    level: 20,
    element: "frost",
    stats: mkStats({ maxHp: 360, spellPower: 58, defense: 12, dodge: 0.15, resistance: { physical: 0, fire: -0.3, frost: 0.5, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_frost_lance", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_ice_high",
    xp: 720,
    gold: [54, 100],
    biome: "ice",
    aiProfile: "spellweaver",
  },

  // Biome: Infernal (extra)
  m_fire_elemental: {
    id: "m_fire_elemental",
    name: "Элементаль огня",
    archetype: "elite",
    level: 20,
    element: "fire",
    stats: mkStats({ maxHp: 420, spellPower: 52, defense: 18, resistance: { physical: 0.1, fire: 0.75, frost: -0.5, shock: 0, void: 0, holy: 0 } }),
    abilities: ["e_infernal_roar", "e_shadow_fang"],
    lootTable: "lt_infernal_mid",
    xp: 620,
    gold: [50, 88],
    biome: "infernal",
  },
  m_inferno_brute: {
    id: "m_inferno_brute",
    name: "Инфернальный великан",
    archetype: "brute",
    level: 24,
    element: "fire",
    stats: mkStats({ maxHp: 800, attack: 72, defense: 36, resistance: { physical: 0.1, fire: 0.5, frost: -0.3, shock: 0, void: 0, holy: -0.2 } }),
    abilities: ["e_slam", "e_infernal_roar"],
    lootTable: "lt_infernal_mid",
    xp: 1100,
    gold: [80, 140],
    biome: "infernal",
  },
  m_shadow_imp: {
    id: "m_shadow_imp",
    name: "Теневой бес",
    archetype: "skirmisher",
    level: 22,
    element: "void",
    stats: mkStats({ maxHp: 320, spellPower: 48, defense: 10, dodge: 0.15, speed: 16 }),
    abilities: ["e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_mid",
    xp: 780,
    gold: [60, 100],
    biome: "abyss",
  },

  // Biome: Abyss (extra)
  m_void_horror: {
    id: "m_void_horror",
    name: "Ужас пустоты",
    archetype: "elite",
    level: 30,
    element: "void",
    stats: mkStats({ maxHp: 980, attack: 98, defense: 40, resistance: { physical: 0.15, fire: 0, frost: 0, shock: 0, void: 0.65, holy: -0.4 } }),
    abilities: ["e_slam", "e_shadow_fang", "e_abyssal_gaze"],
    lootTable: "lt_abyss_high",
    xp: 2200,
    gold: [120, 220],
    biome: "abyss",
    aiProfile: "tactician",
  },
  m_deep_wraith: {
    id: "m_deep_wraith",
    name: "Глубинный призрак",
    archetype: "caster",
    level: 32,
    element: "void",
    stats: mkStats({ maxHp: 760, spellPower: 112, defense: 22, dodge: 0.22 }),
    abilities: ["e_shadow_fang", "e_abyssal_gaze", "e_frost_lance"],
    lootTable: "lt_abyss_high",
    xp: 2800,
    gold: [140, 240],
    biome: "abyss",
    aiProfile: "spellweaver",
  },
  m_forgotten_one: {
    id: "m_forgotten_one",
    name: "Забытый",
    archetype: "elite",
    level: 36,
    element: "void",
    stats: mkStats({ maxHp: 1300, attack: 130, defense: 60, critChance: 0.12, resistance: { physical: 0.2, fire: 0, frost: 0, shock: 0, void: 0.7, holy: -0.5 } }),
    abilities: ["e_slam", "e_abyssal_gaze"],
    lootTable: "lt_abyss_high",
    xp: 4200,
    gold: [220, 380],
    biome: "abyss",
  },
  m_nightmare_crawler: {
    id: "m_nightmare_crawler",
    name: "Кошмарный ползун",
    archetype: "skirmisher",
    level: 38,
    element: "void",
    stats: mkStats({ maxHp: 1100, attack: 118, critChance: 0.15, speed: 18, resistance: { physical: 0.1, fire: 0, frost: 0, shock: 0, void: 0.6, holy: -0.4 } }),
    abilities: ["e_bite", "e_shadow_fang"],
    lootTable: "lt_abyss_high",
    xp: 4800,
    gold: [240, 400],
    biome: "abyss",
  },
};
