import type { PetDef } from "@ton-abyss/shared";

export const PETS: Record<string, PetDef> = {
  pet_emberling: {
    id: "pet_emberling",
    name: "Угольный дракончик",
    family: "wyrm",
    element: "fire",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 120, attack: 18, spellPower: 22, defense: 10, speed: 12, critChance: 0.05 },
    growth: { maxHp: 18, attack: 2.2, spellPower: 2.6, defense: 1.2 },
    abilities: ["basic_strike", "rune_ignite", "power_strike", "rally_pet"],
    passives: ["+5% урон огнём вам и питомцу", "Каждый 5-й удар поджигает"],
    feedTable: { con_minor_hp_potion: 5, con_hp_potion: 25, mat_iron: 2, mat_steel: 8 },
  },
  pet_frost_pup: {
    id: "pet_frost_pup",
    name: "Ледяной щенок",
    family: "beast",
    element: "frost",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 140, attack: 22, defense: 14, speed: 14 },
    growth: { maxHp: 22, attack: 2.8, defense: 1.6 },
    abilities: ["basic_strike", "beast_slash", "power_strike"],
    passives: ["+8% уклонение владельцу", "Каждый 4-й удар замедляет"],
    feedTable: { mat_leather: 2, mat_steel: 8 },
  },
  pet_shadeling: {
    id: "pet_shadeling",
    name: "Теневичок",
    family: "spirit",
    element: "void",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 100, attack: 14, spellPower: 32, defense: 6, dodge: 0.08 },
    growth: { maxHp: 14, spellPower: 3.8, dodge: 0.002 },
    abilities: ["void_drain", "void_curse", "rally_pet"],
    passives: ["+10% вампиризм магии", "Раз в бой воскрешает с 30% HP"],
    feedTable: { mat_void_silk: 30, mat_abyss_shard: 120 },
  },
  pet_stone_golem: {
    id: "pet_stone_golem",
    name: "Каменный голем",
    family: "golem",
    element: "physical",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 320, attack: 24, defense: 30, speed: 6, blockChance: 0.15, blockAmount: 12 },
    growth: { maxHp: 34, attack: 2.0, defense: 3.0 },
    abilities: ["power_strike", "shield_wall"],
    passives: ["Провоцирует врагов", "+15% защита владельцу"],
    feedTable: { mat_iron: 1, mat_steel: 6, mat_mithril: 30 },
  },
  pet_spark_wisp: {
    id: "pet_spark_wisp",
    name: "Искровой огонёк",
    family: "spirit",
    element: "shock",
    rarity: "uncommon",
    maxLevel: 30,
    baseStats: { maxHp: 60, spellPower: 14, dodge: 0.1 },
    growth: { maxHp: 10, spellPower: 2.0 },
    abilities: ["rune_bolt", "basic_strike"],
    passives: ["+4% шанс крита владельцу"],
    feedTable: { mat_iron: 2 },
  },
  pet_snowcat: {
    id: "pet_snowcat",
    name: "Снежный лисик",
    family: "beast",
    element: "frost",
    rarity: "uncommon",
    maxLevel: 35,
    baseStats: { maxHp: 90, attack: 14, speed: 16, dodge: 0.08 },
    growth: { maxHp: 14, attack: 1.8 },
    abilities: ["basic_strike", "beast_slash"],
    passives: ["+5% уклонение владельцу"],
    feedTable: { mat_leather: 3 },
  },
  pet_stoneling: {
    id: "pet_stoneling",
    name: "Каменыш",
    family: "golem",
    element: "physical",
    rarity: "common",
    maxLevel: 25,
    baseStats: { maxHp: 180, defense: 20, speed: 4 },
    growth: { maxHp: 22, defense: 2.0 },
    abilities: ["shield_wall"],
    passives: ["+8% защита владельцу"],
    feedTable: { mat_iron: 3 },
  },
  pet_vine_sprite: {
    id: "pet_vine_sprite",
    name: "Лозовый дух",
    family: "spirit",
    element: "holy",
    rarity: "uncommon",
    maxLevel: 35,
    baseStats: { maxHp: 100, spellPower: 18, defense: 8 },
    growth: { maxHp: 14, spellPower: 2.4 },
    abilities: ["lesser_heal"],
    passives: ["Восстанавливает 2% HP за ход"],
    feedTable: { mat_linen: 4 },
  },
  pet_wraithling: {
    id: "pet_wraithling",
    name: "Малый призрак",
    family: "spirit",
    element: "void",
    rarity: "rare",
    maxLevel: 45,
    baseStats: { maxHp: 130, spellPower: 26, dodge: 0.15 },
    growth: { maxHp: 16, spellPower: 3.2, dodge: 0.002 },
    abilities: ["void_drain"],
    passives: ["+5% уклонение", "+4% вампиризм магии"],
    feedTable: { mat_void_silk: 4 },
  },
  pet_mistwolf: {
    id: "pet_mistwolf",
    name: "Туманный волк",
    family: "beast",
    element: "frost",
    rarity: "epic",
    maxLevel: 55,
    baseStats: { maxHp: 200, attack: 30, speed: 14, critChance: 0.08 },
    growth: { maxHp: 24, attack: 3.0 },
    abilities: ["beast_slash", "power_strike"],
    passives: ["+6% скорость атаки", "Иммунитет к заморозке"],
    feedTable: { mat_leather: 8, mat_mithril: 2 },
  },
  pet_phoenix_chick: {
    id: "pet_phoenix_chick",
    name: "Птенец феникса",
    family: "wyrm",
    element: "fire",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 160, spellPower: 38, defense: 10, resistance: { physical: 0, fire: 0.3, frost: -0.1, shock: 0, void: 0, holy: 0.15 } },
    growth: { maxHp: 20, spellPower: 4.2 },
    abilities: ["rune_ignite", "lesser_heal"],
    passives: ["+10% огненный урон", "Раз в бой воскрешение с 30% HP"],
    feedTable: { mat_phoenix_feather: 1, mat_adamant: 4 },
  },
  pet_thunder_drake: {
    id: "pet_thunder_drake",
    name: "Громовой драконид",
    family: "wyrm",
    element: "shock",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 280, attack: 34, spellPower: 44, speed: 14, critChance: 0.1 },
    growth: { maxHp: 30, attack: 3.4, spellPower: 4.4 },
    abilities: ["rune_bolt", "beast_slash"],
    passives: ["+12% шокового урона", "Молнии цепляют 2 цели"],
    feedTable: { mat_mithril: 6, mat_boss_soul: 2 },
  },
  pet_warden_construct: {
    id: "pet_warden_construct",
    name: "Страж-конструкт",
    family: "golem",
    element: "holy",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 500, attack: 32, defense: 44, blockChance: 0.2, blockAmount: 24 },
    growth: { maxHp: 46, attack: 2.4, defense: 3.8 },
    abilities: ["shield_wall", "power_strike"],
    passives: ["Перенаправляет 12% урона владельца на себя", "+20% защита"],
    feedTable: { mat_adamant: 4, mat_boss_soul: 2 },
  },
  pet_abyss_serpent: {
    id: "pet_abyss_serpent",
    name: "Абиссальный змей",
    family: "abyssal",
    element: "void",
    rarity: "mythic",
    maxLevel: 90,
    baseStats: { maxHp: 260, attack: 36, spellPower: 56, critChance: 0.12, critMultiplier: 0.25 },
    growth: { maxHp: 32, attack: 3.8, spellPower: 5.2, critMultiplier: 0.01 },
    abilities: ["void_drain", "void_curse", "beast_slash"],
    passives: ["+15% крит. урона", "Яд Бездны: 8% урон за ход (стакается)"],
    feedTable: { mat_abyss_shard: 120, mat_boss_soul: 400 },
  },
  pet_abyss_hatchling: {
    id: "pet_abyss_hatchling",
    name: "Детёныш Бездны",
    family: "abyssal",
    element: "void",
    rarity: "mythic",
    maxLevel: 80,
    baseStats: { maxHp: 220, attack: 28, spellPower: 42, defense: 16, speed: 14, critChance: 0.1 },
    growth: { maxHp: 28, attack: 3.2, spellPower: 4.6, defense: 2.0 },
    abilities: ["void_drain", "void_curse", "rally_pet", "rune_bolt"],
    passives: ["+12% магия Бездны", "Шанс 5% поглотить 50% урона", "Раз в день: полный ресет КД"],
    feedTable: { mat_abyss_shard: 100, mat_boss_soul: 500 },
  },
  pet_thunderbird: {
    id: "pet_thunderbird",
    name: "Громовая птица",
    family: "wyrm",
    element: "shock",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 130, attack: 26, spellPower: 28, defense: 8, speed: 22, critChance: 0.08 },
    growth: { maxHp: 16, attack: 2.6, spellPower: 3.0, speed: 0.8 },
    abilities: ["basic_strike", "rune_bolt", "rally_pet"],
    passives: ["+10% шок-урона", "Каждая критика бьёт молнией"],
    feedTable: { mat_steel: 10, mat_obsidian: 30 },
  },
  pet_root_walker: {
    id: "pet_root_walker",
    name: "Корнеходец",
    family: "spirit",
    element: "physical",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 280, attack: 18, defense: 26, speed: 6 },
    growth: { maxHp: 24, defense: 2.0 },
    abilities: ["basic_strike", "power_strike", "rally_pet"],
    passives: ["+12 регена HP/ход", "Раз в бой: накладывает корни (-50% скорости)"],
    feedTable: { mat_leather: 8, mat_obsidian: 25 },
  },
  pet_sand_serpent: {
    id: "pet_sand_serpent",
    name: "Песчаный змей",
    family: "beast",
    element: "physical",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 100, attack: 28, defense: 8, speed: 18, critChance: 0.1 },
    growth: { maxHp: 14, attack: 2.6, speed: 0.6 },
    abilities: ["basic_strike", "beast_slash"],
    passives: ["+5% уклонение", "Шанс 8% яда (DoT 5 ходов)"],
    feedTable: { mat_leather: 4, mat_steel: 6 },
  },
  pet_celestial_owl: {
    id: "pet_celestial_owl",
    name: "Небесная сова",
    family: "wyrm",
    element: "holy",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 120, attack: 18, spellPower: 36, defense: 10, speed: 14, critChance: 0.07 },
    growth: { maxHp: 14, spellPower: 3.4, critChance: 0.001 },
    abilities: ["basic_strike", "rally_pet", "rune_ignite"],
    passives: ["+8% точность владельцу", "Раз в бой: видит все слабости"],
    feedTable: { mat_steel: 12, mat_obsidian: 30 },
  },
  pet_obsidian_crab: {
    id: "pet_obsidian_crab",
    name: "Обсидиановый краб",
    family: "golem",
    element: "physical",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 240, attack: 14, defense: 28, blockChance: 0.2, blockAmount: 15, speed: 4 },
    growth: { maxHp: 22, defense: 1.8, blockAmount: 0.4 },
    abilities: ["basic_strike", "power_strike"],
    passives: ["+15% блок-шанс владельцу", "Шипы: 25% возвращаемого урона"],
    feedTable: { mat_iron: 10, mat_obsidian: 20 },
  },
  pet_phantom_steed: {
    id: "pet_phantom_steed",
    name: "Призрачный конь",
    family: "spirit",
    element: "void",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 200, attack: 32, defense: 12, speed: 24, dodge: 0.1, critChance: 0.08 },
    growth: { maxHp: 22, attack: 3.0, speed: 0.6 },
    abilities: ["basic_strike", "beast_slash", "rally_pet"],
    passives: ["+20 скорости владельцу", "Уклонение 100% раз в 5 ходов"],
    feedTable: { mat_void_silk: 20, mat_abyss_shard: 80 },
  },
  pet_volcano_wyrm: {
    id: "pet_volcano_wyrm",
    name: "Вулканический змей",
    family: "wyrm",
    element: "fire",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 260, attack: 38, spellPower: 42, defense: 18, speed: 12, critChance: 0.1 },
    growth: { maxHp: 26, attack: 3.4, spellPower: 3.8 },
    abilities: ["basic_strike", "rune_ignite", "power_strike", "rally_pet"],
    passives: ["+15% огонь-урона", "Поджог наносит +50% больше урона"],
    feedTable: { mat_steel: 20, mat_obsidian: 50 },
  },
  pet_void_panther: {
    id: "pet_void_panther",
    name: "Пантера Бездны",
    family: "beast",
    element: "void",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 220, attack: 42, spellPower: 18, defense: 14, speed: 22, critChance: 0.15, dodge: 0.08 },
    growth: { maxHp: 22, attack: 3.6, critChance: 0.001 },
    abilities: ["basic_strike", "beast_slash", "void_drain"],
    passives: ["+10% крит. шанса владельцу", "Каждая 3-я атака — теневой шаг"],
    feedTable: { mat_void_silk: 25, mat_abyss_shard: 100 },
  },
  pet_arcane_construct: {
    id: "pet_arcane_construct",
    name: "Аркановый конструкт",
    family: "golem",
    element: "shock",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 280, attack: 22, spellPower: 50, defense: 22, speed: 8, critChance: 0.08 },
    growth: { maxHp: 28, spellPower: 4.2, defense: 2.0 },
    abilities: ["basic_strike", "rune_bolt", "rally_pet"],
    passives: ["+15% макс. маны владельцу", "Восстановление 5% маны при крите"],
    feedTable: { mat_steel: 30, mat_void_silk: 15 },
  },
  pet_kraken_spawn: {
    id: "pet_kraken_spawn",
    name: "Отродье Кракена",
    family: "beast",
    element: "frost",
    rarity: "mythic",
    maxLevel: 80,
    baseStats: { maxHp: 350, attack: 48, spellPower: 30, defense: 24, speed: 10, critChance: 0.1 },
    growth: { maxHp: 32, attack: 4.0, defense: 2.4 },
    abilities: ["basic_strike", "beast_slash", "power_strike", "rune_ignite"],
    passives: ["Захватывает врага на 1 ход (раз в бой)", "+15% сопротивление физ. урону владельцу"],
    feedTable: { mat_void_silk: 40, mat_abyss_shard: 150 },
  },
  pet_phoenix_chick_mythic: {
    id: "pet_phoenix_chick_mythic",
    name: "Птенец Феникса (мифик)",
    family: "wyrm",
    element: "fire",
    rarity: "mythic",
    maxLevel: 80,
    baseStats: { maxHp: 240, attack: 36, spellPower: 52, defense: 16, speed: 18, critChance: 0.12 },
    growth: { maxHp: 24, spellPower: 4.4 },
    abilities: ["basic_strike", "rune_ignite", "rally_pet"],
    passives: ["Раз в бой: воскрешает владельца с 50% HP", "+10% реген HP"],
    feedTable: { mat_obsidian: 80, mat_boss_soul: 300 },
  },
  pet_world_serpent: {
    id: "pet_world_serpent",
    name: "Мировой змей",
    family: "wyrm",
    element: "void",
    rarity: "mythic",
    maxLevel: 80,
    baseStats: { maxHp: 420, attack: 52, spellPower: 38, defense: 28, speed: 12, critChance: 0.13 },
    growth: { maxHp: 36, attack: 4.4, spellPower: 4.0 },
    abilities: ["basic_strike", "void_drain", "power_strike", "rally_pet"],
    passives: ["+20 ко всем основным статам владельца", "Каждый 10-й удар — землетрясение"],
    feedTable: { mat_abyss_shard: 200, mat_boss_soul: 600 },
  },
};
