import type { PetDef } from "@ton-abyss/shared";

export const PETS: Record<string, PetDef> = {
  pet_emberling: {
    id: "pet_emberling",
    name: "Угольный дракончик",
    family: "wyrm",
    element: "fire",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 120, attack: 18, spellPower: 22, defense: 10, speed: 12, critChance: 0.05 },
    growth: { maxHp: 18, attack: 2.2, spellPower: 2.6, defense: 1.2 },
    abilities: ["basic_strike", "rune_ignite", "power_strike", "rally_pet"],
    passives: ["+5% урон огнём вам и питомцу", "Каждый 5-й удар поджигает"],
    feedTable: { con_minor_hp_potion: 5, con_hp_potion: 25, mat_iron: 2, mat_steel: 8 },
  },
  pet_frost_pup: {
    id: "pet_frost_pup",
    name: "Ледяной щенок",
    family: "beast",
    element: "frost",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 140, attack: 22, defense: 14, speed: 14 },
    growth: { maxHp: 22, attack: 2.8, defense: 1.6 },
    abilities: ["basic_strike", "beast_slash", "power_strike"],
    passives: ["+8% уклонение владельцу", "Каждый 4-й удар замедляет"],
    feedTable: { mat_leather: 2, mat_steel: 8 },
  },
  pet_shadeling: {
    id: "pet_shadeling",
    name: "Теневичок",
    family: "spirit",
    element: "void",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 100, attack: 14, spellPower: 32, defense: 6, dodge: 0.08 },
    growth: { maxHp: 14, spellPower: 3.8, dodge: 0.002 },
    abilities: ["void_drain", "void_curse", "rally_pet"],
    passives: ["+10% вампиризм магии", "Раз в бой воскрешает с 30% HP"],
    feedTable: { mat_void_silk: 30, mat_abyss_shard: 120 },
  },
  pet_stone_golem: {
    id: "pet_stone_golem",
    name: "Каменный голем",
    family: "golem",
    element: "physical",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 320, attack: 24, defense: 30, speed: 6, blockChance: 0.15, blockAmount: 12 },
    growth: { maxHp: 34, attack: 2.0, defense: 3.0 },
    abilities: ["power_strike", "shield_wall"],
    passives: ["Провоцирует врагов", "+15% защита владельцу"],
    feedTable: { mat_iron: 1, mat_steel: 6, mat_mithril: 30 },
  },
  pet_abyss_hatchling: {
    id: "pet_abyss_hatchling",
    name: "Детёныш Бездны",
    family: "abyssal",
    element: "void",
    rarity: "mythic",
    maxLevel: 80,
    baseStats: { maxHp: 220, attack: 28, spellPower: 42, defense: 16, speed: 14, critChance: 0.1 },
    growth: { maxHp: 28, attack: 3.2, spellPower: 4.6, defense: 2.0 },
    abilities: ["void_drain", "void_curse", "rally_pet", "rune_bolt"],
    passives: ["+12% магия Бездны", "Шанс 5% поглотить 50% урона", "Раз в день: полный ресет КД"],
    feedTable: { mat_abyss_shard: 100, mat_boss_soul: 500 },
  },
};
