import type { PetDef } from "@ton-abyss/shared";

export const PETS: Record<string, PetDef> = {
  pet_emberling: {
    id: "pet_emberling",
    name: "Угольный дракончик",
    family: "wyrm",
    element: "fire",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 120, attack: 18, spellPower: 22, defense: 10, speed: 12, critChance: 0.05 },
    growth: { maxHp: 18, attack: 2.2, spellPower: 2.6, defense: 1.2 },
    abilities: ["basic_strike", "rune_ignite", "power_strike", "rally_pet"],
    passives: ["+5% урон огнём вам и питомцу", "Каждый 5-й удар поджигает"],
    feedTable: { con_minor_hp_potion: 5, con_hp_potion: 25, mat_iron: 2, mat_steel: 8 },
  },
  pet_frost_pup: {
    id: "pet_frost_pup",
    name: "Ледяной щенок",
    family: "beast",
    element: "frost",
    rarity: "rare",
    maxLevel: 50,
    baseStats: { maxHp: 140, attack: 22, defense: 14, speed: 14 },
    growth: { maxHp: 22, attack: 2.8, defense: 1.6 },
    abilities: ["basic_strike", "beast_slash", "power_strike"],
    passives: ["+8% уклонение владельцу", "Каждый 4-й удар замедляет"],
    feedTable: { mat_leather: 2, mat_steel: 8 },
  },
  pet_shadeling: {
    id: "pet_shadeling",
    name: "Теневичок",
    family: "spirit",
    element: "void",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 100, attack: 14, spellPower: 32, defense: 6, dodge: 0.08 },
    growth: { maxHp: 14, spellPower: 3.8, dodge: 0.002 },
    abilities: ["void_drain", "void_curse", "rally_pet"],
    passives: ["+10% вампиризм магии", "Раз в бой воскрешает с 30% HP"],
    feedTable: { mat_void_silk: 30, mat_abyss_shard: 120 },
  },
  pet_stone_golem: {
    id: "pet_stone_golem",
    name: "Каменный голем",
    family: "golem",
    element: "physical",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 320, attack: 24, defense: 30, speed: 6, blockChance: 0.15, blockAmount: 12 },
    growth: { maxHp: 34, attack: 2.0, defense: 3.0 },
    abilities: ["power_strike", "shield_wall"],
    passives: ["Провоцирует врагов", "+15% защита владельцу"],
    feedTable: { mat_iron: 1, mat_steel: 6, mat_mithril: 30 },
  },
  pet_spark_wisp: {
    id: "pet_spark_wisp",
    name: "Искровой огонёк",
    family: "spirit",
    element: "shock",
    rarity: "uncommon",
    maxLevel: 30,
    baseStats: { maxHp: 60, spellPower: 14, dodge: 0.1 },
    growth: { maxHp: 10, spellPower: 2.0 },
    abilities: ["rune_bolt", "basic_strike"],
    passives: ["+4% шанс крита владельцу"],
    feedTable: { mat_iron: 2 },
  },
  pet_snowcat: {
    id: "pet_snowcat",
    name: "Снежный лисик",
    family: "beast",
    element: "frost",
    rarity: "uncommon",
    maxLevel: 35,
    baseStats: { maxHp: 90, attack: 14, speed: 16, dodge: 0.08 },
    growth: { maxHp: 14, attack: 1.8 },
    abilities: ["basic_strike", "beast_slash"],
    passives: ["+5% уклонение владельцу"],
    feedTable: { mat_leather: 3 },
  },
  pet_stoneling: {
    id: "pet_stoneling",
    name: "Каменыш",
    family: "golem",
    element: "physical",
    rarity: "common",
    maxLevel: 25,
    baseStats: { maxHp: 180, defense: 20, speed: 4 },
    growth: { maxHp: 22, defense: 2.0 },
    abilities: ["shield_wall"],
    passives: ["+8% защита владельцу"],
    feedTable: { mat_iron: 3 },
  },
  pet_vine_sprite: {
    id: "pet_vine_sprite",
    name: "Лозовый дух",
    family: "spirit",
    element: "holy",
    rarity: "uncommon",
    maxLevel: 35,
    baseStats: { maxHp: 100, spellPower: 18, defense: 8 },
    growth: { maxHp: 14, spellPower: 2.4 },
    abilities: ["lesser_heal"],
    passives: ["Восстанавливает 2% HP за ход"],
    feedTable: { mat_linen: 4 },
  },
  pet_wraithling: {
    id: "pet_wraithling",
    name: "Малый призрак",
    family: "spirit",
    element: "void",
    rarity: "rare",
    maxLevel: 45,
    baseStats: { maxHp: 130, spellPower: 26, dodge: 0.15 },
    growth: { maxHp: 16, spellPower: 3.2, dodge: 0.002 },
    abilities: ["void_drain"],
    passives: ["+5% уклонение", "+4% вампиризм магии"],
    feedTable: { mat_void_silk: 4 },
  },
  pet_mistwolf: {
    id: "pet_mistwolf",
    name: "Туманный волк",
    family: "beast",
    element: "frost",
    rarity: "epic",
    maxLevel: 55,
    baseStats: { maxHp: 200, attack: 30, speed: 14, critChance: 0.08 },
    growth: { maxHp: 24, attack: 3.0 },
    abilities: ["beast_slash", "power_strike"],
    passives: ["+6% скорость атаки", "Иммунитет к заморозке"],
    feedTable: { mat_leather: 8, mat_mithril: 2 },
  },
  pet_phoenix_chick: {
    id: "pet_phoenix_chick",
    name: "Птенец феникса",
    family: "wyrm",
    element: "fire",
    rarity: "epic",
    maxLevel: 60,
    baseStats: { maxHp: 160, spellPower: 38, defense: 10, resistance: { physical: 0, fire: 0.3, frost: -0.1, shock: 0, void: 0, holy: 0.15 } },
    growth: { maxHp: 20, spellPower: 4.2 },
    abilities: ["rune_ignite", "lesser_heal"],
    passives: ["+10% огненный урон", "Раз в бой воскрешение с 30% HP"],
    feedTable: { mat_phoenix_feather: 1, mat_adamant: 4 },
  },
  pet_thunder_drake: {
    id: "pet_thunder_drake",
    name: "Громовой драконид",
    family: "wyrm",
    element: "shock",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 280, attack: 34, spellPower: 44, speed: 14, critChance: 0.1 },
    growth: { maxHp: 30, attack: 3.4, spellPower: 4.4 },
    abilities: ["rune_bolt", "beast_slash"],
    passives: ["+12% шокового урона", "Молнии цепляют 2 цели"],
    feedTable: { mat_mithril: 6, mat_boss_soul: 2 },
  },
  pet_warden_construct: {
    id: "pet_warden_construct",
    name: "Страж-конструкт",
    family: "golem",
    element: "holy",
    rarity: "legendary",
    maxLevel: 70,
    baseStats: { maxHp: 500, attack: 32, defense: 44, blockChance: 0.2, blockAmount: 24 },
    growth: { maxHp: 46, attack: 2.4, defense: 3.8 },
    abilities: ["shield_wall", "power_strike"],
    passives: ["Перенаправляет 12% урона владельца на себя", "+20% защита"],
    feedTable: { mat_adamant: 4, mat_boss_soul: 2 },
  },
  pet_abyss_serpent: {
    id: "pet_abyss_serpent",
    name: "Абиссальный змей",
    family: "abyssal",
    element: "void",
    rarity: "mythic",
    maxLevel: 90,
    baseStats: { maxHp: 260, attack: 36, spellPower: 56, critChance: 0.12, critMultiplier: 0.25 },
    growth: { maxHp: 32, attack: 3.8, spellPower: 5.2, critMultiplier: 0.01 },
    abilities: ["void_drain", "void_curse", "beast_slash"],
    passives: ["+15% крит. урона", "Яд Бездны: 8% урон за ход (стакается)"],
    feedTable: { mat_abyss_shard: 120, mat_boss_soul: 400 },
  },
  pet_abyss_hatchling: {
    id: "pet_abyss_hatchling",
    name: "Детёныш Бездны",
    family: "abyssal",
    element: "void",
    rarity: "mythic",
    maxLevel: 80,
    baseStats: { maxHp: 220, attack: 28, spellPower: 42, defense: 16, speed: 14, critChance: 0.1 },
    growth: { maxHp: 28, attack: 3.2, spellPower: 4.6, defense: 2.0 },
    abilities: ["void_drain", "void_curse", "rally_pet", "rune_bolt"],
    passives: ["+12% магия Бездны", "Шанс 5% поглотить 50% урона", "Раз в день: полный ресет КД"],
    feedTable: { mat_abyss_shard: 100, mat_boss_soul: 500 },
  },
};
