import type { QuestDef } from "@ton-abyss/shared";

// Main story: 8 quests. Side: 6. Daily rotating: 6 templates.
export const QUESTS: Record<string, QuestDef> = {
  // ------ MAIN STORY ------
  q_main_01: {
    id: "q_main_01",
    name: "Первое схождение",
    kind: "main",
    levelMin: 1,
    description: "Войдите в Заброшенный склеп и убейте 5 монстров.",
    objectives: [
      { id: "o_kill", kind: "kill_monster", target: "any", amount: 5 },
    ],
    rewards: { gold: 80, xp: 120, items: [{ baseId: "con_hp_potion", qty: 3 }] },
    chain: "q_main_02",
  },
  q_main_02: {
    id: "q_main_02",
    name: "Хозяин склепа",
    kind: "main",
    levelMin: 3,
    description: "Победите Лорда склепа.",
    objectives: [
      { id: "o_boss", kind: "kill_boss", target: "boss_crypt_lord", amount: 1 },
    ],
    rewards: { gold: 400, xp: 800, shards: 5, items: [{ baseId: "key_ice_sanctum", qty: 1 }] },
    chain: "q_main_03",
  },
  q_main_03: {
    id: "q_main_03",
    name: "Зов льда",
    kind: "main",
    levelMin: 8,
    description: "Зачистите Ледяные пещеры и соберите 10 единиц стали.",
    objectives: [
      { id: "o_clear", kind: "clear_dungeon", target: "dng_ice_01", amount: 1 },
      { id: "o_mat", kind: "collect_material", target: "mat_steel", amount: 10 },
    ],
    rewards: { gold: 1200, xp: 2400, items: [{ baseId: "key_infernal", qty: 1 }] },
    chain: "q_main_04",
  },
  q_main_04: {
    id: "q_main_04",
    name: "Преисподняя",
    kind: "main",
    levelMin: 14,
    description: "Докажите свою стойкость в Преисподней.",
    objectives: [
      { id: "o_clear", kind: "clear_dungeon", target: "dng_infernal_01", amount: 1 },
    ],
    rewards: { gold: 5000, xp: 8000, shards: 15, items: [{ baseId: "mat_phoenix_feather", qty: 2 }] },
    chain: "q_main_05",
  },
  q_main_05: {
    id: "q_main_05",
    name: "Оружие мастера",
    kind: "main",
    levelMin: 18,
    description: "Скрафтите стальной меч и достигните эпического качества предмета.",
    objectives: [
      { id: "o_craft", kind: "craft_item", target: "wpn_steel_sword", amount: 1 },
      { id: "o_equip_epic", kind: "equip_rarity", target: "epic", amount: 1 },
    ],
    rewards: { gold: 3000, xp: 6000, abyssDust: 40, skillPoints: 1 },
    chain: "q_main_06",
  },
  q_main_06: {
    id: "q_main_06",
    name: "Следопыт пустоты",
    kind: "main",
    levelMin: 22,
    description: "Найдите путь в Бездну через мертвенные земли.",
    objectives: [
      { id: "o_level", kind: "reach_level", target: "any", amount: 22 },
      { id: "o_dmg", kind: "deal_damage", target: "any", amount: 50000 },
    ],
    rewards: { gold: 8000, xp: 14000, items: [{ baseId: "key_abyss", qty: 1 }] },
    chain: "q_main_07",
  },
  q_main_07: {
    id: "q_main_07",
    name: "Врата Бездны",
    kind: "main",
    levelMin: 28,
    description: "Войдите в Врата Бездны.",
    objectives: [
      { id: "o_clear", kind: "clear_dungeon", target: "dng_abyss_01", amount: 1 },
    ],
    rewards: { gold: 22000, xp: 48000, shards: 40, abyssDust: 200, skillPoints: 2 },
    chain: "q_main_08",
  },
  q_main_08: {
    id: "q_main_08",
    name: "Конец и начало",
    kind: "main",
    levelMin: 40,
    description: "Сразите Титана Бездны и станьте Апексом.",
    objectives: [
      { id: "o_apex", kind: "kill_boss", target: "boss_abyss_titan", amount: 1 },
    ],
    rewards: { gold: 80000, xp: 200000, shards: 100, abyssDust: 1000, skillPoints: 3, title: "Апекс" },
  },

  // ------ SIDE QUESTS ------
  q_side_gathering: {
    id: "q_side_gathering",
    name: "Кузнечное знакомство",
    kind: "side",
    levelMin: 1,
    description: "Соберите 8 железа и 6 кожи для кузнеца.",
    objectives: [
      { id: "o_iron", kind: "collect_material", target: "mat_iron", amount: 8 },
      { id: "o_leather", kind: "collect_material", target: "mat_leather", amount: 6 },
    ],
    rewards: { gold: 200, xp: 200, items: [{ baseId: "con_hp_potion", qty: 5 }] },
  },
  q_side_hunter: {
    id: "q_side_hunter",
    name: "Охотник на нежить",
    kind: "side",
    levelMin: 3,
    description: "Убейте 10 скелетов и 5 упырей.",
    objectives: [
      { id: "o_skel", kind: "kill_monster", target: "m_crypt_skeleton", amount: 10 },
      { id: "o_ghoul", kind: "kill_monster", target: "m_ghoul", amount: 5 },
    ],
    rewards: { gold: 600, xp: 1000, items: [{ baseId: "rune_ward", qty: 1 }] },
  },
  q_side_artisan: {
    id: "q_side_artisan",
    name: "Мастер своего дела",
    kind: "side",
    levelMin: 12,
    description: "Создайте 3 предмета редкого качества или выше.",
    objectives: [
      { id: "o_rare", kind: "equip_rarity", target: "rare", amount: 3 },
    ],
    rewards: { gold: 2200, xp: 4000, abyssDust: 25 },
  },
  q_side_socketer: {
    id: "q_side_socketer",
    name: "Гранильщик",
    kind: "side",
    levelMin: 14,
    description: "Вставьте 5 гемов в предметы.",
    objectives: [
      { id: "o_socket", kind: "socket_gem", target: "any", amount: 5 },
    ],
    rewards: { gold: 3200, xp: 4800, items: [{ baseId: "mat_mithril", qty: 5 }] },
  },
  q_side_legendary: {
    id: "q_side_legendary",
    name: "Легенда во плоти",
    kind: "side",
    levelMin: 25,
    description: "Экипируйте легендарный предмет.",
    objectives: [
      { id: "o_leg", kind: "equip_rarity", target: "legendary", amount: 1 },
    ],
    rewards: { gold: 15000, xp: 20000, shards: 30, skillPoints: 1 },
  },
  q_side_endgame: {
    id: "q_side_endgame",
    name: "Покоритель данжей",
    kind: "side",
    levelMin: 30,
    description: "Зачистите 10 данжей.",
    objectives: [
      { id: "o_dungeons", kind: "clear_dungeon", target: "any", amount: 10 },
    ],
    rewards: { gold: 40000, xp: 80000, shards: 50, skillPoints: 2, title: "Покоритель" },
  },

  // ------ DAILY BOUNTIES ------
  q_daily_gold: {
    id: "q_daily_gold",
    name: "Дань алчности",
    kind: "daily",
    levelMin: 5,
    description: "Убейте 30 монстров.",
    objectives: [{ id: "o_kills", kind: "kill_monster", target: "any", amount: 30 }],
    rewards: { gold: 1200, xp: 800 },
    cooldownSeconds: 86400,
  },
  q_daily_boss: {
    id: "q_daily_boss",
    name: "Дневной охотник",
    kind: "daily",
    levelMin: 10,
    description: "Победите босса.",
    objectives: [{ id: "o_boss", kind: "kill_boss", target: "any", amount: 1 }],
    rewards: { gold: 3000, xp: 2500, items: [{ baseId: "mat_boss_soul", qty: 1 }] },
    cooldownSeconds: 86400,
  },
  q_daily_craft: {
    id: "q_daily_craft",
    name: "Дневная кузня",
    kind: "daily",
    levelMin: 5,
    description: "Скрафтите 1 предмет.",
    objectives: [{ id: "o_craft", kind: "craft_item", target: "any", amount: 1 }],
    rewards: { gold: 800, xp: 400, items: [{ baseId: "mat_iron", qty: 5 }] },
    cooldownSeconds: 86400,
  },
  q_daily_socket: {
    id: "q_daily_socket",
    name: "Огранка дня",
    kind: "daily",
    levelMin: 15,
    description: "Вставьте 2 гема.",
    objectives: [{ id: "o_socket", kind: "socket_gem", target: "any", amount: 2 }],
    rewards: { gold: 1600, xp: 1200, abyssDust: 10 },
    cooldownSeconds: 86400,
  },
  q_daily_dungeon: {
    id: "q_daily_dungeon",
    name: "Покоритель подземелий",
    kind: "daily",
    levelMin: 8,
    description: "Зачистите данж.",
    objectives: [{ id: "o_clear", kind: "clear_dungeon", target: "any", amount: 1 }],
    rewards: { gold: 2400, xp: 2000, shards: 3 },
    cooldownSeconds: 86400,
  },
  q_daily_damage: {
    id: "q_daily_damage",
    name: "Разрушитель",
    kind: "daily",
    levelMin: 20,
    description: "Нанесите 100 000 урона.",
    objectives: [{ id: "o_dmg", kind: "deal_damage", target: "any", amount: 100000 }],
    rewards: { gold: 4000, xp: 3000, abyssDust: 25 },
    cooldownSeconds: 86400,
  },
};
