import type { RecipeDef } from "@ton-abyss/shared";

export const RECIPES: Record<string, RecipeDef> = {
  r_iron_sword: {
    id: "r_iron_sword",
    name: "Ковка: железный меч",
    outputBaseId: "wpn_iron_sword",
    outputLevel: 6,
    inputs: [
      { baseId: "mat_iron", qty: 4 },
      { baseId: "mat_leather", qty: 2 },
    ],
    goldCost: 120,
    stationTier: 1,
    unlockedBy: "default",
    rarityBias: { common: 0, uncommon: 600, rare: 200, epic: 40, legendary: 5, mythic: 0.3, abyssal: 0 },
  },
  r_steel_sword: {
    id: "r_steel_sword",
    name: "Ковка: стальной меч",
    outputBaseId: "wpn_steel_sword",
    outputLevel: 14,
    inputs: [
      { baseId: "mat_steel", qty: 5 },
      { baseId: "mat_iron", qty: 6 },
    ],
    goldCost: 650,
    stationTier: 2,
    unlockedBy: "default",
    rarityBias: { uncommon: 500, rare: 300, epic: 70, legendary: 12, mythic: 0.6, abyssal: 0 },
  },
  r_arcane_staff: {
    id: "r_arcane_staff",
    name: "Эншантинг: посох чародея",
    outputBaseId: "wpn_arcane_staff",
    outputLevel: 12,
    inputs: [
      { baseId: "mat_steel", qty: 4 },
      { baseId: "mat_phoenix_feather", qty: 1 },
      { baseId: "rune_flame", qty: 1 },
    ],
    goldCost: 900,
    stationTier: 2,
    unlockedBy: "drop",
    rarityBias: { uncommon: 400, rare: 350, epic: 100, legendary: 20, mythic: 1.2, abyssal: 0 },
  },
  r_robe_of_runes: {
    id: "r_robe_of_runes",
    name: "Ткачество: одежды рун",
    outputBaseId: "arm_robe_of_runes",
    outputLevel: 14,
    inputs: [
      { baseId: "mat_linen", qty: 12 },
      { baseId: "mat_phoenix_feather", qty: 1 },
    ],
    goldCost: 700,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_void_tome: {
    id: "r_void_tome",
    name: "Эншантинг: фолиант Бездны",
    outputBaseId: "wpn_void_tome",
    outputLevel: 28,
    inputs: [
      { baseId: "mat_void_silk", qty: 6 },
      { baseId: "mat_abyss_shard", qty: 3 },
      { baseId: "mat_boss_soul", qty: 1 },
    ],
    goldCost: 9000,
    stationTier: 4,
    unlockedBy: "quest",
    rarityBias: { rare: 250, epic: 400, legendary: 120, mythic: 12, abyssal: 0.5 },
  },
  r_abyssal_edge: {
    id: "r_abyssal_edge",
    name: "Бездонная ковка: клинок Бездны",
    outputBaseId: "wpn_abyssal_edge",
    outputLevel: 42,
    inputs: [
      { baseId: "mat_adamant", qty: 6 },
      { baseId: "mat_abyss_shard", qty: 8 },
      { baseId: "mat_boss_soul", qty: 3 },
      { baseId: "mat_phoenix_feather", qty: 2 },
    ],
    goldCost: 65000,
    stationTier: 5,
    unlockedBy: "reputation",
    rarityBias: { epic: 400, legendary: 300, mythic: 60, abyssal: 4 },
  },
};
