import type { RecipeDef } from "@ton-abyss/shared";

export const RECIPES: Record<string, RecipeDef> = {
  r_iron_sword: {
    id: "r_iron_sword",
    name: "Ковка: железный меч",
    outputBaseId: "wpn_iron_sword",
    outputLevel: 6,
    inputs: [
      { baseId: "mat_iron", qty: 4 },
      { baseId: "mat_leather", qty: 2 },
    ],
    goldCost: 120,
    stationTier: 1,
    unlockedBy: "default",
    rarityBias: { common: 0, uncommon: 600, rare: 200, epic: 40, legendary: 5, mythic: 0.3, abyssal: 0 },
  },
  r_steel_sword: {
    id: "r_steel_sword",
    name: "Ковка: стальной меч",
    outputBaseId: "wpn_steel_sword",
    outputLevel: 14,
    inputs: [
      { baseId: "mat_steel", qty: 5 },
      { baseId: "mat_iron", qty: 6 },
    ],
    goldCost: 650,
    stationTier: 2,
    unlockedBy: "default",
    rarityBias: { uncommon: 500, rare: 300, epic: 70, legendary: 12, mythic: 0.6, abyssal: 0 },
  },
  r_arcane_staff: {
    id: "r_arcane_staff",
    name: "Эншантинг: посох чародея",
    outputBaseId: "wpn_arcane_staff",
    outputLevel: 12,
    inputs: [
      { baseId: "mat_steel", qty: 4 },
      { baseId: "mat_phoenix_feather", qty: 1 },
      { baseId: "rune_flame", qty: 1 },
    ],
    goldCost: 900,
    stationTier: 2,
    unlockedBy: "drop",
    rarityBias: { uncommon: 400, rare: 350, epic: 100, legendary: 20, mythic: 1.2, abyssal: 0 },
  },
  r_robe_of_runes: {
    id: "r_robe_of_runes",
    name: "Ткачество: одежды рун",
    outputBaseId: "arm_robe_of_runes",
    outputLevel: 14,
    inputs: [
      { baseId: "mat_linen", qty: 12 },
      { baseId: "mat_phoenix_feather", qty: 1 },
    ],
    goldCost: 700,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_void_tome: {
    id: "r_void_tome",
    name: "Эншантинг: фолиант Бездны",
    outputBaseId: "wpn_void_tome",
    outputLevel: 28,
    inputs: [
      { baseId: "mat_void_silk", qty: 6 },
      { baseId: "mat_abyss_shard", qty: 3 },
      { baseId: "mat_boss_soul", qty: 1 },
    ],
    goldCost: 9000,
    stationTier: 4,
    unlockedBy: "quest",
    rarityBias: { rare: 250, epic: 400, legendary: 120, mythic: 12, abyssal: 0.5 },
  },
  r_abyssal_edge: {
    id: "r_abyssal_edge",
    name: "Бездонная ковка: клинок Бездны",
    outputBaseId: "wpn_abyssal_edge",
    outputLevel: 42,
    inputs: [
      { baseId: "mat_adamant", qty: 6 },
      { baseId: "mat_abyss_shard", qty: 8 },
      { baseId: "mat_boss_soul", qty: 3 },
      { baseId: "mat_phoenix_feather", qty: 2 },
    ],
    goldCost: 65000,
    stationTier: 5,
    unlockedBy: "reputation",
    rarityBias: { epic: 400, legendary: 300, mythic: 60, abyssal: 4 },
  },

  // ==== Tier 2 crafts ====
  r_mithril_sword: {
    id: "r_mithril_sword",
    name: "Ковка: мифриловый меч",
    outputBaseId: "wpn_mithril_sword",
    outputLevel: 22,
    inputs: [{ baseId: "mat_mithril", qty: 4 }, { baseId: "mat_steel", qty: 8 }],
    goldCost: 2400,
    stationTier: 3,
    unlockedBy: "default",
    rarityBias: { rare: 300, epic: 120, legendary: 18, mythic: 1, abyssal: 0 },
  },
  r_warhammer: {
    id: "r_warhammer",
    name: "Ковка: боевой молот",
    outputBaseId: "wpn_warhammer",
    outputLevel: 14,
    inputs: [{ baseId: "mat_steel", qty: 6 }, { baseId: "mat_iron", qty: 8 }],
    goldCost: 900,
    stationTier: 2,
    unlockedBy: "default",
    rarityBias: { uncommon: 400, rare: 250, epic: 60, legendary: 10, mythic: 0.5, abyssal: 0 },
  },
  r_silver_bow: {
    id: "r_silver_bow",
    name: "Резьба: серебряный лук",
    outputBaseId: "wpn_silver_bow",
    outputLevel: 10,
    inputs: [{ baseId: "mat_leather", qty: 6 }, { baseId: "mat_linen", qty: 8 }, { baseId: "mat_iron", qty: 2 }],
    goldCost: 500,
    stationTier: 1,
    unlockedBy: "default",
  },
  r_ember_bow: {
    id: "r_ember_bow",
    name: "Резьба: лук углей",
    outputBaseId: "wpn_ember_bow",
    outputLevel: 26,
    inputs: [{ baseId: "mat_mithril", qty: 3 }, { baseId: "mat_phoenix_feather", qty: 2 }, { baseId: "rune_flame", qty: 1 }],
    goldCost: 7200,
    stationTier: 3,
    unlockedBy: "drop",
    rarityBias: { rare: 200, epic: 300, legendary: 45, mythic: 3, abyssal: 0 },
  },
  r_wand_frost: {
    id: "r_wand_frost",
    name: "Эншантинг: жезл стужи",
    outputBaseId: "wpn_wand_of_frost",
    outputLevel: 8,
    inputs: [{ baseId: "mat_linen", qty: 8 }, { baseId: "mat_iron", qty: 2 }, { baseId: "rune_ward", qty: 1 }],
    goldCost: 300,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_wand_shadow: {
    id: "r_wand_shadow",
    name: "Эншантинг: жезл тени",
    outputBaseId: "wpn_wand_of_shadow",
    outputLevel: 16,
    inputs: [{ baseId: "mat_void_silk", qty: 2 }, { baseId: "mat_mithril", qty: 2 }, { baseId: "rune_flame", qty: 1 }],
    goldCost: 1400,
    stationTier: 3,
    unlockedBy: "drop",
    rarityBias: { rare: 300, epic: 150, legendary: 20, mythic: 1, abyssal: 0 },
  },
  r_staff_storms: {
    id: "r_staff_storms",
    name: "Эншантинг: посох бурь",
    outputBaseId: "wpn_staff_of_storms",
    outputLevel: 20,
    inputs: [{ baseId: "mat_mithril", qty: 4 }, { baseId: "mat_phoenix_feather", qty: 1 }, { baseId: "rune_flame", qty: 1 }],
    goldCost: 3600,
    stationTier: 3,
    unlockedBy: "default",
    rarityBias: { rare: 250, epic: 250, legendary: 40, mythic: 2, abyssal: 0 },
  },
  r_celestial_staff: {
    id: "r_celestial_staff",
    name: "Небесная ковка: небесный посох",
    outputBaseId: "wpn_celestial_staff",
    outputLevel: 32,
    inputs: [{ baseId: "mat_adamant", qty: 3 }, { baseId: "mat_abyss_shard", qty: 2 }, { baseId: "mat_phoenix_feather", qty: 3 }],
    goldCost: 18000,
    stationTier: 4,
    unlockedBy: "reputation",
    rarityBias: { epic: 300, legendary: 180, mythic: 18, abyssal: 1 },
  },
  r_feral_claws: {
    id: "r_feral_claws",
    name: "Ковка: одичалые когти",
    outputBaseId: "wpn_feral_claws",
    outputLevel: 14,
    inputs: [{ baseId: "mat_steel", qty: 4 }, { baseId: "mat_leather", qty: 6 }],
    goldCost: 700,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_abyss_claws: {
    id: "r_abyss_claws",
    name: "Бездонная ковка: когти Бездны",
    outputBaseId: "wpn_abyss_claws",
    outputLevel: 32,
    inputs: [{ baseId: "mat_adamant", qty: 4 }, { baseId: "mat_abyss_shard", qty: 5 }, { baseId: "mat_void_silk", qty: 4 }],
    goldCost: 22000,
    stationTier: 5,
    unlockedBy: "quest",
    rarityBias: { epic: 350, legendary: 240, mythic: 30, abyssal: 2 },
  },
  r_titan_greatsword: {
    id: "r_titan_greatsword",
    name: "Ковка: титанский двуручник",
    outputBaseId: "wpn_titan_greatsword",
    outputLevel: 38,
    inputs: [{ baseId: "mat_adamant", qty: 8 }, { baseId: "mat_mithril", qty: 10 }, { baseId: "mat_boss_soul", qty: 2 }],
    goldCost: 42000,
    stationTier: 5,
    unlockedBy: "quest",
    rarityBias: { epic: 400, legendary: 220, mythic: 28, abyssal: 1 },
  },
  r_tome_eternity: {
    id: "r_tome_eternity",
    name: "Эншантинг: фолиант вечности",
    outputBaseId: "wpn_tome_of_eternity",
    outputLevel: 48,
    inputs: [{ baseId: "mat_adamant", qty: 10 }, { baseId: "mat_abyss_shard", qty: 14 }, { baseId: "mat_boss_soul", qty: 5 }, { baseId: "mat_phoenix_feather", qty: 4 }],
    goldCost: 120000,
    stationTier: 5,
    unlockedBy: "reputation",
    rarityBias: { legendary: 400, mythic: 90, abyssal: 6 },
  },
  // ==== Armor crafts ====
  r_mithril_hauberk: {
    id: "r_mithril_hauberk",
    name: "Кольчуга из мифрила",
    outputBaseId: "arm_mithril_hauberk",
    outputLevel: 22,
    inputs: [{ baseId: "mat_mithril", qty: 6 }, { baseId: "mat_steel", qty: 10 }],
    goldCost: 3400,
    stationTier: 3,
    unlockedBy: "default",
    rarityBias: { rare: 300, epic: 140, legendary: 18, mythic: 1, abyssal: 0 },
  },
  r_dragon_mail: {
    id: "r_dragon_mail",
    name: "Ковка: драконья чешуя",
    outputBaseId: "arm_dragon_mail",
    outputLevel: 30,
    inputs: [{ baseId: "mat_adamant", qty: 4 }, { baseId: "mat_phoenix_feather", qty: 2 }, { baseId: "mat_mithril", qty: 8 }],
    goldCost: 14000,
    stationTier: 4,
    unlockedBy: "quest",
    rarityBias: { epic: 300, legendary: 200, mythic: 24, abyssal: 1 },
  },
  r_shadow_cowl: {
    id: "r_shadow_cowl",
    name: "Ткачество: теневой мантек",
    outputBaseId: "arm_shadow_cowl",
    outputLevel: 26,
    inputs: [{ baseId: "mat_void_silk", qty: 10 }, { baseId: "mat_leather", qty: 8 }],
    goldCost: 6200,
    stationTier: 3,
    unlockedBy: "drop",
    rarityBias: { rare: 250, epic: 250, legendary: 40, mythic: 2, abyssal: 0 },
  },
  r_celestial_vestment: {
    id: "r_celestial_vestment",
    name: "Ткачество: небесное одеяние",
    outputBaseId: "arm_celestial_vestment",
    outputLevel: 40,
    inputs: [{ baseId: "mat_void_silk", qty: 14 }, { baseId: "mat_abyss_shard", qty: 6 }, { baseId: "mat_phoenix_feather", qty: 4 }],
    goldCost: 52000,
    stationTier: 5,
    unlockedBy: "reputation",
    rarityBias: { epic: 350, legendary: 250, mythic: 32, abyssal: 2 },
  },
  // ==== Trinket crafts ====
  r_amulet_fortitude: {
    id: "r_amulet_fortitude",
    name: "Ювелирка: амулет стойкости",
    outputBaseId: "tr_amulet_of_fortitude",
    outputLevel: 14,
    inputs: [{ baseId: "mat_steel", qty: 4 }, { baseId: "mat_leather", qty: 3 }],
    goldCost: 1200,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_amulet_flame: {
    id: "r_amulet_flame",
    name: "Ювелирка: амулет пламени",
    outputBaseId: "tr_amulet_of_flame",
    outputLevel: 20,
    inputs: [{ baseId: "mat_mithril", qty: 2 }, { baseId: "mat_phoenix_feather", qty: 1 }, { baseId: "rune_flame", qty: 1 }],
    goldCost: 4200,
    stationTier: 3,
    unlockedBy: "drop",
  },
  r_amulet_shadow: {
    id: "r_amulet_shadow",
    name: "Ювелирка: амулет тени",
    outputBaseId: "tr_amulet_of_shadow",
    outputLevel: 24,
    inputs: [{ baseId: "mat_mithril", qty: 3 }, { baseId: "mat_void_silk", qty: 4 }, { baseId: "rune_ward", qty: 1 }],
    goldCost: 7800,
    stationTier: 4,
    unlockedBy: "drop",
  },
  r_amulet_abyss: {
    id: "r_amulet_abyss",
    name: "Ювелирка: амулет Бездны",
    outputBaseId: "tr_amulet_of_abyss",
    outputLevel: 38,
    inputs: [{ baseId: "mat_abyss_shard", qty: 6 }, { baseId: "mat_adamant", qty: 3 }, { baseId: "mat_boss_soul", qty: 1 }],
    goldCost: 38000,
    stationTier: 5,
    unlockedBy: "reputation",
    rarityBias: { epic: 300, legendary: 250, mythic: 35, abyssal: 3 },
  },
  r_ring_kings: {
    id: "r_ring_kings",
    name: "Ювелирка: королевское кольцо",
    outputBaseId: "tr_ring_of_kings",
    outputLevel: 30,
    inputs: [{ baseId: "mat_mithril", qty: 6 }, { baseId: "mat_adamant", qty: 2 }, { baseId: "mat_phoenix_feather", qty: 1 }],
    goldCost: 18000,
    stationTier: 4,
    unlockedBy: "quest",
  },
  r_ring_abyss: {
    id: "r_ring_abyss",
    name: "Ювелирка: кольцо Бездны",
    outputBaseId: "tr_ring_of_abyss",
    outputLevel: 40,
    inputs: [{ baseId: "mat_abyss_shard", qty: 10 }, { baseId: "mat_adamant", qty: 4 }, { baseId: "mat_boss_soul", qty: 2 }],
    goldCost: 48000,
    stationTier: 5,
    unlockedBy: "reputation",
    rarityBias: { epic: 300, legendary: 260, mythic: 40, abyssal: 3 },
  },
  // ==== Consumable crafts ====
  r_elixir_might: {
    id: "r_elixir_might",
    name: "Алхимия: эликсир мощи",
    outputBaseId: "con_elixir_of_might",
    outputLevel: 15,
    inputs: [{ baseId: "mat_steel", qty: 1 }, { baseId: "mat_leather", qty: 1 }],
    goldCost: 120,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_elixir_mind: {
    id: "r_elixir_mind",
    name: "Алхимия: эликсир разума",
    outputBaseId: "con_elixir_of_mind",
    outputLevel: 15,
    inputs: [{ baseId: "mat_linen", qty: 4 }, { baseId: "mat_steel", qty: 1 }],
    goldCost: 120,
    stationTier: 2,
    unlockedBy: "default",
  },
  r_phoenix_heal: {
    id: "r_phoenix_heal",
    name: "Алхимия: перо феникса",
    outputBaseId: "con_phoenix_feather_heal",
    outputLevel: 30,
    inputs: [{ baseId: "mat_phoenix_feather", qty: 1 }, { baseId: "mat_mithril", qty: 2 }],
    goldCost: 2400,
    stationTier: 4,
    unlockedBy: "drop",
  },
  r_abyss_essence: {
    id: "r_abyss_essence",
    name: "Алхимия: эссенция Бездны",
    outputBaseId: "con_abyss_essence",
    outputLevel: 40,
    inputs: [{ baseId: "mat_abyss_shard", qty: 3 }, { baseId: "mat_boss_soul", qty: 1 }],
    goldCost: 8000,
    stationTier: 5,
    unlockedBy: "reputation",
  },
};
